// Code generated by ent, DO NOT EDIT.

package lotteryattemptgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotteryattemptgrant type in the database.
	Label = "lottery_attempt_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRequestKey holds the string denoting the request_key field in the database.
	FieldRequestKey = "request_key"
	// FieldTargetAll holds the string denoting the target_all field in the database.
	FieldTargetAll = "target_all"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the lotteryattemptgrant in the database.
	Table = "lottery_attempt_grants"
)

// Columns holds all SQL columns for lotteryattemptgrant fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldRequestKey,
	FieldTargetAll,
	FieldAmount,
	FieldDescription,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestKeyValidator is a validator for the "request_key" field. It is called by the builders before save.
	RequestKeyValidator func(string) error
	// DefaultTargetAll holds the default value on creation for the "target_all" field.
	DefaultTargetAll bool
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryAttemptGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRequestKey orders the results by the request_key field.
func ByRequestKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestKey, opts...).ToFunc()
}

// ByTargetAll orders the results by the target_all field.
func ByTargetAll(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetAll, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
