// Code generated by ent, DO NOT EDIT.

package lotterydraw

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotterydraw type in the database.
	Label = "lottery_draw"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldPrizeID holds the string denoting the prize_id field in the database.
	FieldPrizeID = "prize_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPrizeName holds the string denoting the prize_name field in the database.
	FieldPrizeName = "prize_name"
	// FieldPrizeType holds the string denoting the prize_type field in the database.
	FieldPrizeType = "prize_type"
	// FieldBalanceAmount holds the string denoting the balance_amount field in the database.
	FieldBalanceAmount = "balance_amount"
	// FieldProductContent holds the string denoting the product_content field in the database.
	FieldProductContent = "product_content"
	// FieldAttemptKey holds the string denoting the attempt_key field in the database.
	FieldAttemptKey = "attempt_key"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeActivity holds the string denoting the activity edge name in mutations.
	EdgeActivity = "activity"
	// EdgePrize holds the string denoting the prize edge name in mutations.
	EdgePrize = "prize"
	// Table holds the table name of the lotterydraw in the database.
	Table = "lottery_draws"
	// ActivityTable is the table that holds the activity relation/edge.
	ActivityTable = "lottery_draws"
	// ActivityInverseTable is the table name for the LotteryActivity entity.
	// It exists in this package in order to avoid circular dependency with the "lotteryactivity" package.
	ActivityInverseTable = "lottery_activities"
	// ActivityColumn is the table column denoting the activity relation/edge.
	ActivityColumn = "activity_id"
	// PrizeTable is the table that holds the prize relation/edge.
	PrizeTable = "lottery_draws"
	// PrizeInverseTable is the table name for the LotteryPrize entity.
	// It exists in this package in order to avoid circular dependency with the "lotteryprize" package.
	PrizeInverseTable = "lottery_prizes"
	// PrizeColumn is the table column denoting the prize relation/edge.
	PrizeColumn = "prize_id"
)

// Columns holds all SQL columns for lotterydraw fields.
var Columns = []string{
	FieldID,
	FieldActivityID,
	FieldPrizeID,
	FieldUserID,
	FieldPrizeName,
	FieldPrizeType,
	FieldBalanceAmount,
	FieldProductContent,
	FieldAttemptKey,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrizeNameValidator is a validator for the "prize_name" field. It is called by the builders before save.
	PrizeNameValidator func(string) error
	// PrizeTypeValidator is a validator for the "prize_type" field. It is called by the builders before save.
	PrizeTypeValidator func(string) error
	// AttemptKeyValidator is a validator for the "attempt_key" field. It is called by the builders before save.
	AttemptKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryDraw queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByPrizeID orders the results by the prize_id field.
func ByPrizeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPrizeName orders the results by the prize_name field.
func ByPrizeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeName, opts...).ToFunc()
}

// ByPrizeType orders the results by the prize_type field.
func ByPrizeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeType, opts...).ToFunc()
}

// ByBalanceAmount orders the results by the balance_amount field.
func ByBalanceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAmount, opts...).ToFunc()
}

// ByProductContent orders the results by the product_content field.
func ByProductContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductContent, opts...).ToFunc()
}

// ByAttemptKey orders the results by the attempt_key field.
func ByAttemptKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByActivityField orders the results by activity field.
func ByActivityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivityStep(), sql.OrderByField(field, opts...))
	}
}

// ByPrizeField orders the results by prize field.
func ByPrizeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrizeStep(), sql.OrderByField(field, opts...))
	}
}
func newActivityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
	)
}
func newPrizeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrizeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrizeTable, PrizeColumn),
	)
}
