// Code generated by ent, DO NOT EDIT.

package usercustomgroupmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usercustomgroupmodel type in the database.
	Label = "user_custom_group_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCustomGroupID holds the string denoting the custom_group_id field in the database.
	FieldCustomGroupID = "custom_group_id"
	// FieldPublicModel holds the string denoting the public_model field in the database.
	FieldPublicModel = "public_model"
	// FieldSourceGroupID holds the string denoting the source_group_id field in the database.
	FieldSourceGroupID = "source_group_id"
	// FieldSourceModel holds the string denoting the source_model field in the database.
	FieldSourceModel = "source_model"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCustomGroup holds the string denoting the custom_group edge name in mutations.
	EdgeCustomGroup = "custom_group"
	// EdgeSourceGroup holds the string denoting the source_group edge name in mutations.
	EdgeSourceGroup = "source_group"
	// Table holds the table name of the usercustomgroupmodel in the database.
	Table = "user_custom_group_models"
	// CustomGroupTable is the table that holds the custom_group relation/edge.
	CustomGroupTable = "user_custom_group_models"
	// CustomGroupInverseTable is the table name for the UserCustomGroup entity.
	// It exists in this package in order to avoid circular dependency with the "usercustomgroup" package.
	CustomGroupInverseTable = "user_custom_groups"
	// CustomGroupColumn is the table column denoting the custom_group relation/edge.
	CustomGroupColumn = "custom_group_id"
	// SourceGroupTable is the table that holds the source_group relation/edge.
	SourceGroupTable = "user_custom_group_models"
	// SourceGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	SourceGroupInverseTable = "groups"
	// SourceGroupColumn is the table column denoting the source_group relation/edge.
	SourceGroupColumn = "source_group_id"
)

// Columns holds all SQL columns for usercustomgroupmodel fields.
var Columns = []string{
	FieldID,
	FieldCustomGroupID,
	FieldPublicModel,
	FieldSourceGroupID,
	FieldSourceModel,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	PublicModelValidator func(string) error
	// SourceModelValidator is a validator for the "source_model" field. It is called by the builders before save.
	SourceModelValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserCustomGroupModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCustomGroupID orders the results by the custom_group_id field.
func ByCustomGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomGroupID, opts...).ToFunc()
}

// ByPublicModel orders the results by the public_model field.
func ByPublicModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicModel, opts...).ToFunc()
}

// BySourceGroupID orders the results by the source_group_id field.
func BySourceGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceGroupID, opts...).ToFunc()
}

// BySourceModel orders the results by the source_model field.
func BySourceModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceModel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCustomGroupField orders the results by custom_group field.
func ByCustomGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomGroupStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceGroupField orders the results by source_group field.
func BySourceGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newCustomGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CustomGroupTable, CustomGroupColumn),
	)
}
func newSourceGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceGroupTable, SourceGroupColumn),
	)
}
