// Code generated by ent, DO NOT EDIT.

package emptyresponseclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the emptyresponseclaim type in the database.
	Label = "empty_response_claim"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldOutcomeID holds the string denoting the outcome_id field in the database.
	FieldOutcomeID = "outcome_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReasonCode holds the string denoting the reason_code field in the database.
	FieldReasonCode = "reason_code"
	// FieldUserReason holds the string denoting the user_reason field in the database.
	FieldUserReason = "user_reason"
	// FieldAdminNote holds the string denoting the admin_note field in the database.
	FieldAdminNote = "admin_note"
	// FieldOriginalActualCost holds the string denoting the original_actual_cost field in the database.
	FieldOriginalActualCost = "original_actual_cost"
	// FieldBalanceRefund holds the string denoting the balance_refund field in the database.
	FieldBalanceRefund = "balance_refund"
	// FieldSubscriptionRefund holds the string denoting the subscription_refund field in the database.
	FieldSubscriptionRefund = "subscription_refund"
	// FieldAPIKeyQuotaRefund holds the string denoting the api_key_quota_refund field in the database.
	FieldAPIKeyQuotaRefund = "api_key_quota_refund"
	// FieldEvidence holds the string denoting the evidence field in the database.
	FieldEvidence = "evidence"
	// FieldRuleVersion holds the string denoting the rule_version field in the database.
	FieldRuleVersion = "rule_version"
	// FieldReviewedBy holds the string denoting the reviewed_by field in the database.
	FieldReviewedBy = "reviewed_by"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldCompensatedAt holds the string denoting the compensated_at field in the database.
	FieldCompensatedAt = "compensated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the emptyresponseclaim in the database.
	Table = "empty_response_claims"
)

// Columns holds all SQL columns for emptyresponseclaim fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldOutcomeID,
	FieldUserID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldSubscriptionID,
	FieldStatus,
	FieldReasonCode,
	FieldUserReason,
	FieldAdminNote,
	FieldOriginalActualCost,
	FieldBalanceRefund,
	FieldSubscriptionRefund,
	FieldAPIKeyQuotaRefund,
	FieldEvidence,
	FieldRuleVersion,
	FieldReviewedBy,
	FieldReviewedAt,
	FieldCompensatedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultReasonCode holds the default value on creation for the "reason_code" field.
	DefaultReasonCode string
	// ReasonCodeValidator is a validator for the "reason_code" field. It is called by the builders before save.
	ReasonCodeValidator func(string) error
	// DefaultUserReason holds the default value on creation for the "user_reason" field.
	DefaultUserReason string
	// UserReasonValidator is a validator for the "user_reason" field. It is called by the builders before save.
	UserReasonValidator func(string) error
	// DefaultAdminNote holds the default value on creation for the "admin_note" field.
	DefaultAdminNote string
	// DefaultOriginalActualCost holds the default value on creation for the "original_actual_cost" field.
	DefaultOriginalActualCost float64
	// DefaultBalanceRefund holds the default value on creation for the "balance_refund" field.
	DefaultBalanceRefund float64
	// DefaultSubscriptionRefund holds the default value on creation for the "subscription_refund" field.
	DefaultSubscriptionRefund float64
	// DefaultAPIKeyQuotaRefund holds the default value on creation for the "api_key_quota_refund" field.
	DefaultAPIKeyQuotaRefund float64
	// DefaultRuleVersion holds the default value on creation for the "rule_version" field.
	DefaultRuleVersion int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the EmptyResponseClaim queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByOutcomeID orders the results by the outcome_id field.
func ByOutcomeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcomeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReasonCode orders the results by the reason_code field.
func ByReasonCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasonCode, opts...).ToFunc()
}

// ByUserReason orders the results by the user_reason field.
func ByUserReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserReason, opts...).ToFunc()
}

// ByAdminNote orders the results by the admin_note field.
func ByAdminNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNote, opts...).ToFunc()
}

// ByOriginalActualCost orders the results by the original_actual_cost field.
func ByOriginalActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalActualCost, opts...).ToFunc()
}

// ByBalanceRefund orders the results by the balance_refund field.
func ByBalanceRefund(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceRefund, opts...).ToFunc()
}

// BySubscriptionRefund orders the results by the subscription_refund field.
func BySubscriptionRefund(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionRefund, opts...).ToFunc()
}

// ByAPIKeyQuotaRefund orders the results by the api_key_quota_refund field.
func ByAPIKeyQuotaRefund(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyQuotaRefund, opts...).ToFunc()
}

// ByRuleVersion orders the results by the rule_version field.
func ByRuleVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleVersion, opts...).ToFunc()
}

// ByReviewedBy orders the results by the reviewed_by field.
func ByReviewedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedBy, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByCompensatedAt orders the results by the compensated_at field.
func ByCompensatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompensatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
