// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/emptyresponseclaim"
)

// EmptyResponseClaimCreate is the builder for creating a EmptyResponseClaim entity.
type EmptyResponseClaimCreate struct {
	config
	mutation *EmptyResponseClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *EmptyResponseClaimCreate) SetUsageLogID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetOutcomeID sets the "outcome_id" field.
func (_c *EmptyResponseClaimCreate) SetOutcomeID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetOutcomeID(v)
	return _c
}

// SetNillableOutcomeID sets the "outcome_id" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableOutcomeID(v *int64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetOutcomeID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EmptyResponseClaimCreate) SetUserID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *EmptyResponseClaimCreate) SetAPIKeyID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *EmptyResponseClaimCreate) SetAccountID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EmptyResponseClaimCreate) SetGroupID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableGroupID(v *int64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *EmptyResponseClaimCreate) SetSubscriptionID(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableSubscriptionID(v *int64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EmptyResponseClaimCreate) SetStatus(v string) *EmptyResponseClaimCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableStatus(v *string) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReasonCode sets the "reason_code" field.
func (_c *EmptyResponseClaimCreate) SetReasonCode(v string) *EmptyResponseClaimCreate {
	_c.mutation.SetReasonCode(v)
	return _c
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableReasonCode(v *string) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetReasonCode(*v)
	}
	return _c
}

// SetUserReason sets the "user_reason" field.
func (_c *EmptyResponseClaimCreate) SetUserReason(v string) *EmptyResponseClaimCreate {
	_c.mutation.SetUserReason(v)
	return _c
}

// SetNillableUserReason sets the "user_reason" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableUserReason(v *string) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetUserReason(*v)
	}
	return _c
}

// SetAdminNote sets the "admin_note" field.
func (_c *EmptyResponseClaimCreate) SetAdminNote(v string) *EmptyResponseClaimCreate {
	_c.mutation.SetAdminNote(v)
	return _c
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableAdminNote(v *string) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetAdminNote(*v)
	}
	return _c
}

// SetOriginalActualCost sets the "original_actual_cost" field.
func (_c *EmptyResponseClaimCreate) SetOriginalActualCost(v float64) *EmptyResponseClaimCreate {
	_c.mutation.SetOriginalActualCost(v)
	return _c
}

// SetNillableOriginalActualCost sets the "original_actual_cost" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableOriginalActualCost(v *float64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetOriginalActualCost(*v)
	}
	return _c
}

// SetBalanceRefund sets the "balance_refund" field.
func (_c *EmptyResponseClaimCreate) SetBalanceRefund(v float64) *EmptyResponseClaimCreate {
	_c.mutation.SetBalanceRefund(v)
	return _c
}

// SetNillableBalanceRefund sets the "balance_refund" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableBalanceRefund(v *float64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetBalanceRefund(*v)
	}
	return _c
}

// SetSubscriptionRefund sets the "subscription_refund" field.
func (_c *EmptyResponseClaimCreate) SetSubscriptionRefund(v float64) *EmptyResponseClaimCreate {
	_c.mutation.SetSubscriptionRefund(v)
	return _c
}

// SetNillableSubscriptionRefund sets the "subscription_refund" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableSubscriptionRefund(v *float64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetSubscriptionRefund(*v)
	}
	return _c
}

// SetAPIKeyQuotaRefund sets the "api_key_quota_refund" field.
func (_c *EmptyResponseClaimCreate) SetAPIKeyQuotaRefund(v float64) *EmptyResponseClaimCreate {
	_c.mutation.SetAPIKeyQuotaRefund(v)
	return _c
}

// SetNillableAPIKeyQuotaRefund sets the "api_key_quota_refund" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableAPIKeyQuotaRefund(v *float64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetAPIKeyQuotaRefund(*v)
	}
	return _c
}

// SetEvidence sets the "evidence" field.
func (_c *EmptyResponseClaimCreate) SetEvidence(v map[string]interface{}) *EmptyResponseClaimCreate {
	_c.mutation.SetEvidence(v)
	return _c
}

// SetRuleVersion sets the "rule_version" field.
func (_c *EmptyResponseClaimCreate) SetRuleVersion(v int) *EmptyResponseClaimCreate {
	_c.mutation.SetRuleVersion(v)
	return _c
}

// SetNillableRuleVersion sets the "rule_version" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableRuleVersion(v *int) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetRuleVersion(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *EmptyResponseClaimCreate) SetReviewedBy(v int64) *EmptyResponseClaimCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableReviewedBy(v *int64) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *EmptyResponseClaimCreate) SetReviewedAt(v time.Time) *EmptyResponseClaimCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableReviewedAt(v *time.Time) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCompensatedAt sets the "compensated_at" field.
func (_c *EmptyResponseClaimCreate) SetCompensatedAt(v time.Time) *EmptyResponseClaimCreate {
	_c.mutation.SetCompensatedAt(v)
	return _c
}

// SetNillableCompensatedAt sets the "compensated_at" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableCompensatedAt(v *time.Time) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetCompensatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmptyResponseClaimCreate) SetCreatedAt(v time.Time) *EmptyResponseClaimCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableCreatedAt(v *time.Time) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmptyResponseClaimCreate) SetUpdatedAt(v time.Time) *EmptyResponseClaimCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmptyResponseClaimCreate) SetNillableUpdatedAt(v *time.Time) *EmptyResponseClaimCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the EmptyResponseClaimMutation object of the builder.
func (_c *EmptyResponseClaimCreate) Mutation() *EmptyResponseClaimMutation {
	return _c.mutation
}

// Save creates the EmptyResponseClaim in the database.
func (_c *EmptyResponseClaimCreate) Save(ctx context.Context) (*EmptyResponseClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmptyResponseClaimCreate) SaveX(ctx context.Context) *EmptyResponseClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmptyResponseClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmptyResponseClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmptyResponseClaimCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := emptyresponseclaim.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ReasonCode(); !ok {
		v := emptyresponseclaim.DefaultReasonCode
		_c.mutation.SetReasonCode(v)
	}
	if _, ok := _c.mutation.UserReason(); !ok {
		v := emptyresponseclaim.DefaultUserReason
		_c.mutation.SetUserReason(v)
	}
	if _, ok := _c.mutation.AdminNote(); !ok {
		v := emptyresponseclaim.DefaultAdminNote
		_c.mutation.SetAdminNote(v)
	}
	if _, ok := _c.mutation.OriginalActualCost(); !ok {
		v := emptyresponseclaim.DefaultOriginalActualCost
		_c.mutation.SetOriginalActualCost(v)
	}
	if _, ok := _c.mutation.BalanceRefund(); !ok {
		v := emptyresponseclaim.DefaultBalanceRefund
		_c.mutation.SetBalanceRefund(v)
	}
	if _, ok := _c.mutation.SubscriptionRefund(); !ok {
		v := emptyresponseclaim.DefaultSubscriptionRefund
		_c.mutation.SetSubscriptionRefund(v)
	}
	if _, ok := _c.mutation.APIKeyQuotaRefund(); !ok {
		v := emptyresponseclaim.DefaultAPIKeyQuotaRefund
		_c.mutation.SetAPIKeyQuotaRefund(v)
	}
	if _, ok := _c.mutation.RuleVersion(); !ok {
		v := emptyresponseclaim.DefaultRuleVersion
		_c.mutation.SetRuleVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emptyresponseclaim.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emptyresponseclaim.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmptyResponseClaimCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "EmptyResponseClaim.usage_log_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EmptyResponseClaim.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "EmptyResponseClaim.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "EmptyResponseClaim.account_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EmptyResponseClaim.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := emptyresponseclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmptyResponseClaim.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReasonCode(); !ok {
		return &ValidationError{Name: "reason_code", err: errors.New(`ent: missing required field "EmptyResponseClaim.reason_code"`)}
	}
	if v, ok := _c.mutation.ReasonCode(); ok {
		if err := emptyresponseclaim.ReasonCodeValidator(v); err != nil {
			return &ValidationError{Name: "reason_code", err: fmt.Errorf(`ent: validator failed for field "EmptyResponseClaim.reason_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserReason(); !ok {
		return &ValidationError{Name: "user_reason", err: errors.New(`ent: missing required field "EmptyResponseClaim.user_reason"`)}
	}
	if v, ok := _c.mutation.UserReason(); ok {
		if err := emptyresponseclaim.UserReasonValidator(v); err != nil {
			return &ValidationError{Name: "user_reason", err: fmt.Errorf(`ent: validator failed for field "EmptyResponseClaim.user_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AdminNote(); !ok {
		return &ValidationError{Name: "admin_note", err: errors.New(`ent: missing required field "EmptyResponseClaim.admin_note"`)}
	}
	if _, ok := _c.mutation.OriginalActualCost(); !ok {
		return &ValidationError{Name: "original_actual_cost", err: errors.New(`ent: missing required field "EmptyResponseClaim.original_actual_cost"`)}
	}
	if _, ok := _c.mutation.BalanceRefund(); !ok {
		return &ValidationError{Name: "balance_refund", err: errors.New(`ent: missing required field "EmptyResponseClaim.balance_refund"`)}
	}
	if _, ok := _c.mutation.SubscriptionRefund(); !ok {
		return &ValidationError{Name: "subscription_refund", err: errors.New(`ent: missing required field "EmptyResponseClaim.subscription_refund"`)}
	}
	if _, ok := _c.mutation.APIKeyQuotaRefund(); !ok {
		return &ValidationError{Name: "api_key_quota_refund", err: errors.New(`ent: missing required field "EmptyResponseClaim.api_key_quota_refund"`)}
	}
	if _, ok := _c.mutation.RuleVersion(); !ok {
		return &ValidationError{Name: "rule_version", err: errors.New(`ent: missing required field "EmptyResponseClaim.rule_version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmptyResponseClaim.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmptyResponseClaim.updated_at"`)}
	}
	return nil
}

func (_c *EmptyResponseClaimCreate) sqlSave(ctx context.Context) (*EmptyResponseClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmptyResponseClaimCreate) createSpec() (*EmptyResponseClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &EmptyResponseClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emptyresponseclaim.Table, sqlgraph.NewFieldSpec(emptyresponseclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(emptyresponseclaim.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = value
	}
	if value, ok := _c.mutation.OutcomeID(); ok {
		_spec.SetField(emptyresponseclaim.FieldOutcomeID, field.TypeInt64, value)
		_node.OutcomeID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(emptyresponseclaim.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(emptyresponseclaim.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(emptyresponseclaim.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(emptyresponseclaim.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(emptyresponseclaim.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(emptyresponseclaim.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReasonCode(); ok {
		_spec.SetField(emptyresponseclaim.FieldReasonCode, field.TypeString, value)
		_node.ReasonCode = value
	}
	if value, ok := _c.mutation.UserReason(); ok {
		_spec.SetField(emptyresponseclaim.FieldUserReason, field.TypeString, value)
		_node.UserReason = value
	}
	if value, ok := _c.mutation.AdminNote(); ok {
		_spec.SetField(emptyresponseclaim.FieldAdminNote, field.TypeString, value)
		_node.AdminNote = value
	}
	if value, ok := _c.mutation.OriginalActualCost(); ok {
		_spec.SetField(emptyresponseclaim.FieldOriginalActualCost, field.TypeFloat64, value)
		_node.OriginalActualCost = value
	}
	if value, ok := _c.mutation.BalanceRefund(); ok {
		_spec.SetField(emptyresponseclaim.FieldBalanceRefund, field.TypeFloat64, value)
		_node.BalanceRefund = value
	}
	if value, ok := _c.mutation.SubscriptionRefund(); ok {
		_spec.SetField(emptyresponseclaim.FieldSubscriptionRefund, field.TypeFloat64, value)
		_node.SubscriptionRefund = value
	}
	if value, ok := _c.mutation.APIKeyQuotaRefund(); ok {
		_spec.SetField(emptyresponseclaim.FieldAPIKeyQuotaRefund, field.TypeFloat64, value)
		_node.APIKeyQuotaRefund = value
	}
	if value, ok := _c.mutation.Evidence(); ok {
		_spec.SetField(emptyresponseclaim.FieldEvidence, field.TypeJSON, value)
		_node.Evidence = value
	}
	if value, ok := _c.mutation.RuleVersion(); ok {
		_spec.SetField(emptyresponseclaim.FieldRuleVersion, field.TypeInt, value)
		_node.RuleVersion = value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(emptyresponseclaim.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(emptyresponseclaim.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CompensatedAt(); ok {
		_spec.SetField(emptyresponseclaim.FieldCompensatedAt, field.TypeTime, value)
		_node.CompensatedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emptyresponseclaim.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emptyresponseclaim.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmptyResponseClaim.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmptyResponseClaimUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *EmptyResponseClaimCreate) OnConflict(opts ...sql.ConflictOption) *EmptyResponseClaimUpsertOne {
	_c.conflict = opts
	return &EmptyResponseClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmptyResponseClaimCreate) OnConflictColumns(columns ...string) *EmptyResponseClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmptyResponseClaimUpsertOne{
		create: _c,
	}
}

type (
	// EmptyResponseClaimUpsertOne is the builder for "upsert"-ing
	//  one EmptyResponseClaim node.
	EmptyResponseClaimUpsertOne struct {
		create *EmptyResponseClaimCreate
	}

	// EmptyResponseClaimUpsert is the "OnConflict" setter.
	EmptyResponseClaimUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *EmptyResponseClaimUpsert) SetUsageLogID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateUsageLogID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EmptyResponseClaimUpsert) AddUsageLogID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldUsageLogID, v)
	return u
}

// SetOutcomeID sets the "outcome_id" field.
func (u *EmptyResponseClaimUpsert) SetOutcomeID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldOutcomeID, v)
	return u
}

// UpdateOutcomeID sets the "outcome_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateOutcomeID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldOutcomeID)
	return u
}

// AddOutcomeID adds v to the "outcome_id" field.
func (u *EmptyResponseClaimUpsert) AddOutcomeID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldOutcomeID, v)
	return u
}

// ClearOutcomeID clears the value of the "outcome_id" field.
func (u *EmptyResponseClaimUpsert) ClearOutcomeID() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldOutcomeID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EmptyResponseClaimUpsert) SetUserID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateUserID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *EmptyResponseClaimUpsert) AddUserID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EmptyResponseClaimUpsert) SetAPIKeyID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateAPIKeyID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EmptyResponseClaimUpsert) AddAPIKeyID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldAPIKeyID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *EmptyResponseClaimUpsert) SetAccountID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateAccountID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *EmptyResponseClaimUpsert) AddAccountID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldAccountID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EmptyResponseClaimUpsert) SetGroupID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateGroupID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *EmptyResponseClaimUpsert) AddGroupID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EmptyResponseClaimUpsert) ClearGroupID() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldGroupID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *EmptyResponseClaimUpsert) SetSubscriptionID(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateSubscriptionID() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *EmptyResponseClaimUpsert) AddSubscriptionID(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldSubscriptionID, v)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *EmptyResponseClaimUpsert) ClearSubscriptionID() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldSubscriptionID)
	return u
}

// SetStatus sets the "status" field.
func (u *EmptyResponseClaimUpsert) SetStatus(v string) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateStatus() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldStatus)
	return u
}

// SetReasonCode sets the "reason_code" field.
func (u *EmptyResponseClaimUpsert) SetReasonCode(v string) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldReasonCode, v)
	return u
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateReasonCode() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldReasonCode)
	return u
}

// SetUserReason sets the "user_reason" field.
func (u *EmptyResponseClaimUpsert) SetUserReason(v string) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldUserReason, v)
	return u
}

// UpdateUserReason sets the "user_reason" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateUserReason() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldUserReason)
	return u
}

// SetAdminNote sets the "admin_note" field.
func (u *EmptyResponseClaimUpsert) SetAdminNote(v string) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldAdminNote, v)
	return u
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateAdminNote() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldAdminNote)
	return u
}

// SetOriginalActualCost sets the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsert) SetOriginalActualCost(v float64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldOriginalActualCost, v)
	return u
}

// UpdateOriginalActualCost sets the "original_actual_cost" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateOriginalActualCost() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldOriginalActualCost)
	return u
}

// AddOriginalActualCost adds v to the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsert) AddOriginalActualCost(v float64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldOriginalActualCost, v)
	return u
}

// SetBalanceRefund sets the "balance_refund" field.
func (u *EmptyResponseClaimUpsert) SetBalanceRefund(v float64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldBalanceRefund, v)
	return u
}

// UpdateBalanceRefund sets the "balance_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateBalanceRefund() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldBalanceRefund)
	return u
}

// AddBalanceRefund adds v to the "balance_refund" field.
func (u *EmptyResponseClaimUpsert) AddBalanceRefund(v float64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldBalanceRefund, v)
	return u
}

// SetSubscriptionRefund sets the "subscription_refund" field.
func (u *EmptyResponseClaimUpsert) SetSubscriptionRefund(v float64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldSubscriptionRefund, v)
	return u
}

// UpdateSubscriptionRefund sets the "subscription_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateSubscriptionRefund() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldSubscriptionRefund)
	return u
}

// AddSubscriptionRefund adds v to the "subscription_refund" field.
func (u *EmptyResponseClaimUpsert) AddSubscriptionRefund(v float64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldSubscriptionRefund, v)
	return u
}

// SetAPIKeyQuotaRefund sets the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsert) SetAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldAPIKeyQuotaRefund, v)
	return u
}

// UpdateAPIKeyQuotaRefund sets the "api_key_quota_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateAPIKeyQuotaRefund() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldAPIKeyQuotaRefund)
	return u
}

// AddAPIKeyQuotaRefund adds v to the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsert) AddAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldAPIKeyQuotaRefund, v)
	return u
}

// SetEvidence sets the "evidence" field.
func (u *EmptyResponseClaimUpsert) SetEvidence(v map[string]interface{}) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldEvidence, v)
	return u
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateEvidence() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldEvidence)
	return u
}

// ClearEvidence clears the value of the "evidence" field.
func (u *EmptyResponseClaimUpsert) ClearEvidence() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldEvidence)
	return u
}

// SetRuleVersion sets the "rule_version" field.
func (u *EmptyResponseClaimUpsert) SetRuleVersion(v int) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldRuleVersion, v)
	return u
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateRuleVersion() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldRuleVersion)
	return u
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *EmptyResponseClaimUpsert) AddRuleVersion(v int) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldRuleVersion, v)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *EmptyResponseClaimUpsert) SetReviewedBy(v int64) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateReviewedBy() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *EmptyResponseClaimUpsert) AddReviewedBy(v int64) *EmptyResponseClaimUpsert {
	u.Add(emptyresponseclaim.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *EmptyResponseClaimUpsert) ClearReviewedBy() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldReviewedBy)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *EmptyResponseClaimUpsert) SetReviewedAt(v time.Time) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateReviewedAt() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *EmptyResponseClaimUpsert) ClearReviewedAt() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldReviewedAt)
	return u
}

// SetCompensatedAt sets the "compensated_at" field.
func (u *EmptyResponseClaimUpsert) SetCompensatedAt(v time.Time) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldCompensatedAt, v)
	return u
}

// UpdateCompensatedAt sets the "compensated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateCompensatedAt() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldCompensatedAt)
	return u
}

// ClearCompensatedAt clears the value of the "compensated_at" field.
func (u *EmptyResponseClaimUpsert) ClearCompensatedAt() *EmptyResponseClaimUpsert {
	u.SetNull(emptyresponseclaim.FieldCompensatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmptyResponseClaimUpsert) SetUpdatedAt(v time.Time) *EmptyResponseClaimUpsert {
	u.Set(emptyresponseclaim.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsert) UpdateUpdatedAt() *EmptyResponseClaimUpsert {
	u.SetExcluded(emptyresponseclaim.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmptyResponseClaimUpsertOne) UpdateNewValues() *EmptyResponseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emptyresponseclaim.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmptyResponseClaimUpsertOne) Ignore() *EmptyResponseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmptyResponseClaimUpsertOne) DoNothing() *EmptyResponseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmptyResponseClaimCreate.OnConflict
// documentation for more info.
func (u *EmptyResponseClaimUpsertOne) Update(set func(*EmptyResponseClaimUpsert)) *EmptyResponseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmptyResponseClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *EmptyResponseClaimUpsertOne) SetUsageLogID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EmptyResponseClaimUpsertOne) AddUsageLogID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateUsageLogID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetOutcomeID sets the "outcome_id" field.
func (u *EmptyResponseClaimUpsertOne) SetOutcomeID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetOutcomeID(v)
	})
}

// AddOutcomeID adds v to the "outcome_id" field.
func (u *EmptyResponseClaimUpsertOne) AddOutcomeID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddOutcomeID(v)
	})
}

// UpdateOutcomeID sets the "outcome_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateOutcomeID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateOutcomeID()
	})
}

// ClearOutcomeID clears the value of the "outcome_id" field.
func (u *EmptyResponseClaimUpsertOne) ClearOutcomeID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearOutcomeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmptyResponseClaimUpsertOne) SetUserID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EmptyResponseClaimUpsertOne) AddUserID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateUserID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EmptyResponseClaimUpsertOne) SetAPIKeyID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EmptyResponseClaimUpsertOne) AddAPIKeyID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateAPIKeyID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *EmptyResponseClaimUpsertOne) SetAccountID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *EmptyResponseClaimUpsertOne) AddAccountID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateAccountID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EmptyResponseClaimUpsertOne) SetGroupID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *EmptyResponseClaimUpsertOne) AddGroupID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateGroupID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EmptyResponseClaimUpsertOne) ClearGroupID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *EmptyResponseClaimUpsertOne) SetSubscriptionID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *EmptyResponseClaimUpsertOne) AddSubscriptionID(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateSubscriptionID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *EmptyResponseClaimUpsertOne) ClearSubscriptionID() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetStatus sets the "status" field.
func (u *EmptyResponseClaimUpsertOne) SetStatus(v string) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateStatus() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetReasonCode sets the "reason_code" field.
func (u *EmptyResponseClaimUpsertOne) SetReasonCode(v string) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReasonCode(v)
	})
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateReasonCode() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReasonCode()
	})
}

// SetUserReason sets the "user_reason" field.
func (u *EmptyResponseClaimUpsertOne) SetUserReason(v string) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUserReason(v)
	})
}

// UpdateUserReason sets the "user_reason" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateUserReason() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUserReason()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *EmptyResponseClaimUpsertOne) SetAdminNote(v string) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateAdminNote() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAdminNote()
	})
}

// SetOriginalActualCost sets the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsertOne) SetOriginalActualCost(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetOriginalActualCost(v)
	})
}

// AddOriginalActualCost adds v to the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsertOne) AddOriginalActualCost(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddOriginalActualCost(v)
	})
}

// UpdateOriginalActualCost sets the "original_actual_cost" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateOriginalActualCost() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateOriginalActualCost()
	})
}

// SetBalanceRefund sets the "balance_refund" field.
func (u *EmptyResponseClaimUpsertOne) SetBalanceRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetBalanceRefund(v)
	})
}

// AddBalanceRefund adds v to the "balance_refund" field.
func (u *EmptyResponseClaimUpsertOne) AddBalanceRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddBalanceRefund(v)
	})
}

// UpdateBalanceRefund sets the "balance_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateBalanceRefund() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateBalanceRefund()
	})
}

// SetSubscriptionRefund sets the "subscription_refund" field.
func (u *EmptyResponseClaimUpsertOne) SetSubscriptionRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetSubscriptionRefund(v)
	})
}

// AddSubscriptionRefund adds v to the "subscription_refund" field.
func (u *EmptyResponseClaimUpsertOne) AddSubscriptionRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddSubscriptionRefund(v)
	})
}

// UpdateSubscriptionRefund sets the "subscription_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateSubscriptionRefund() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateSubscriptionRefund()
	})
}

// SetAPIKeyQuotaRefund sets the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsertOne) SetAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAPIKeyQuotaRefund(v)
	})
}

// AddAPIKeyQuotaRefund adds v to the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsertOne) AddAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAPIKeyQuotaRefund(v)
	})
}

// UpdateAPIKeyQuotaRefund sets the "api_key_quota_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateAPIKeyQuotaRefund() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAPIKeyQuotaRefund()
	})
}

// SetEvidence sets the "evidence" field.
func (u *EmptyResponseClaimUpsertOne) SetEvidence(v map[string]interface{}) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateEvidence() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateEvidence()
	})
}

// ClearEvidence clears the value of the "evidence" field.
func (u *EmptyResponseClaimUpsertOne) ClearEvidence() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearEvidence()
	})
}

// SetRuleVersion sets the "rule_version" field.
func (u *EmptyResponseClaimUpsertOne) SetRuleVersion(v int) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetRuleVersion(v)
	})
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *EmptyResponseClaimUpsertOne) AddRuleVersion(v int) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddRuleVersion(v)
	})
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateRuleVersion() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateRuleVersion()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertOne) SetReviewedBy(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertOne) AddReviewedBy(v int64) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateReviewedBy() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertOne) ClearReviewedBy() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *EmptyResponseClaimUpsertOne) SetReviewedAt(v time.Time) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateReviewedAt() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *EmptyResponseClaimUpsertOne) ClearReviewedAt() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompensatedAt sets the "compensated_at" field.
func (u *EmptyResponseClaimUpsertOne) SetCompensatedAt(v time.Time) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetCompensatedAt(v)
	})
}

// UpdateCompensatedAt sets the "compensated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateCompensatedAt() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateCompensatedAt()
	})
}

// ClearCompensatedAt clears the value of the "compensated_at" field.
func (u *EmptyResponseClaimUpsertOne) ClearCompensatedAt() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearCompensatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmptyResponseClaimUpsertOne) SetUpdatedAt(v time.Time) *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertOne) UpdateUpdatedAt() *EmptyResponseClaimUpsertOne {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmptyResponseClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmptyResponseClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmptyResponseClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmptyResponseClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmptyResponseClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmptyResponseClaimCreateBulk is the builder for creating many EmptyResponseClaim entities in bulk.
type EmptyResponseClaimCreateBulk struct {
	config
	err      error
	builders []*EmptyResponseClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the EmptyResponseClaim entities in the database.
func (_c *EmptyResponseClaimCreateBulk) Save(ctx context.Context) ([]*EmptyResponseClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmptyResponseClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmptyResponseClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmptyResponseClaimCreateBulk) SaveX(ctx context.Context) []*EmptyResponseClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmptyResponseClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmptyResponseClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmptyResponseClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmptyResponseClaimUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *EmptyResponseClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmptyResponseClaimUpsertBulk {
	_c.conflict = opts
	return &EmptyResponseClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmptyResponseClaimCreateBulk) OnConflictColumns(columns ...string) *EmptyResponseClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmptyResponseClaimUpsertBulk{
		create: _c,
	}
}

// EmptyResponseClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of EmptyResponseClaim nodes.
type EmptyResponseClaimUpsertBulk struct {
	create *EmptyResponseClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmptyResponseClaimUpsertBulk) UpdateNewValues() *EmptyResponseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emptyresponseclaim.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmptyResponseClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmptyResponseClaimUpsertBulk) Ignore() *EmptyResponseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmptyResponseClaimUpsertBulk) DoNothing() *EmptyResponseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmptyResponseClaimCreateBulk.OnConflict
// documentation for more info.
func (u *EmptyResponseClaimUpsertBulk) Update(set func(*EmptyResponseClaimUpsert)) *EmptyResponseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmptyResponseClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetUsageLogID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddUsageLogID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateUsageLogID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetOutcomeID sets the "outcome_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetOutcomeID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetOutcomeID(v)
	})
}

// AddOutcomeID adds v to the "outcome_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddOutcomeID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddOutcomeID(v)
	})
}

// UpdateOutcomeID sets the "outcome_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateOutcomeID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateOutcomeID()
	})
}

// ClearOutcomeID clears the value of the "outcome_id" field.
func (u *EmptyResponseClaimUpsertBulk) ClearOutcomeID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearOutcomeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetUserID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddUserID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateUserID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetAPIKeyID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddAPIKeyID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateAPIKeyID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetAccountID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddAccountID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateAccountID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetGroupID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddGroupID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateGroupID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EmptyResponseClaimUpsertBulk) ClearGroupID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *EmptyResponseClaimUpsertBulk) SetSubscriptionID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *EmptyResponseClaimUpsertBulk) AddSubscriptionID(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateSubscriptionID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *EmptyResponseClaimUpsertBulk) ClearSubscriptionID() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetStatus sets the "status" field.
func (u *EmptyResponseClaimUpsertBulk) SetStatus(v string) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateStatus() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetReasonCode sets the "reason_code" field.
func (u *EmptyResponseClaimUpsertBulk) SetReasonCode(v string) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReasonCode(v)
	})
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateReasonCode() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReasonCode()
	})
}

// SetUserReason sets the "user_reason" field.
func (u *EmptyResponseClaimUpsertBulk) SetUserReason(v string) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUserReason(v)
	})
}

// UpdateUserReason sets the "user_reason" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateUserReason() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUserReason()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *EmptyResponseClaimUpsertBulk) SetAdminNote(v string) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateAdminNote() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAdminNote()
	})
}

// SetOriginalActualCost sets the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsertBulk) SetOriginalActualCost(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetOriginalActualCost(v)
	})
}

// AddOriginalActualCost adds v to the "original_actual_cost" field.
func (u *EmptyResponseClaimUpsertBulk) AddOriginalActualCost(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddOriginalActualCost(v)
	})
}

// UpdateOriginalActualCost sets the "original_actual_cost" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateOriginalActualCost() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateOriginalActualCost()
	})
}

// SetBalanceRefund sets the "balance_refund" field.
func (u *EmptyResponseClaimUpsertBulk) SetBalanceRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetBalanceRefund(v)
	})
}

// AddBalanceRefund adds v to the "balance_refund" field.
func (u *EmptyResponseClaimUpsertBulk) AddBalanceRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddBalanceRefund(v)
	})
}

// UpdateBalanceRefund sets the "balance_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateBalanceRefund() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateBalanceRefund()
	})
}

// SetSubscriptionRefund sets the "subscription_refund" field.
func (u *EmptyResponseClaimUpsertBulk) SetSubscriptionRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetSubscriptionRefund(v)
	})
}

// AddSubscriptionRefund adds v to the "subscription_refund" field.
func (u *EmptyResponseClaimUpsertBulk) AddSubscriptionRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddSubscriptionRefund(v)
	})
}

// UpdateSubscriptionRefund sets the "subscription_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateSubscriptionRefund() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateSubscriptionRefund()
	})
}

// SetAPIKeyQuotaRefund sets the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsertBulk) SetAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetAPIKeyQuotaRefund(v)
	})
}

// AddAPIKeyQuotaRefund adds v to the "api_key_quota_refund" field.
func (u *EmptyResponseClaimUpsertBulk) AddAPIKeyQuotaRefund(v float64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddAPIKeyQuotaRefund(v)
	})
}

// UpdateAPIKeyQuotaRefund sets the "api_key_quota_refund" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateAPIKeyQuotaRefund() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateAPIKeyQuotaRefund()
	})
}

// SetEvidence sets the "evidence" field.
func (u *EmptyResponseClaimUpsertBulk) SetEvidence(v map[string]interface{}) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateEvidence() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateEvidence()
	})
}

// ClearEvidence clears the value of the "evidence" field.
func (u *EmptyResponseClaimUpsertBulk) ClearEvidence() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearEvidence()
	})
}

// SetRuleVersion sets the "rule_version" field.
func (u *EmptyResponseClaimUpsertBulk) SetRuleVersion(v int) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetRuleVersion(v)
	})
}

// AddRuleVersion adds v to the "rule_version" field.
func (u *EmptyResponseClaimUpsertBulk) AddRuleVersion(v int) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddRuleVersion(v)
	})
}

// UpdateRuleVersion sets the "rule_version" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateRuleVersion() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateRuleVersion()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertBulk) SetReviewedBy(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertBulk) AddReviewedBy(v int64) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateReviewedBy() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *EmptyResponseClaimUpsertBulk) ClearReviewedBy() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *EmptyResponseClaimUpsertBulk) SetReviewedAt(v time.Time) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateReviewedAt() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *EmptyResponseClaimUpsertBulk) ClearReviewedAt() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompensatedAt sets the "compensated_at" field.
func (u *EmptyResponseClaimUpsertBulk) SetCompensatedAt(v time.Time) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetCompensatedAt(v)
	})
}

// UpdateCompensatedAt sets the "compensated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateCompensatedAt() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateCompensatedAt()
	})
}

// ClearCompensatedAt clears the value of the "compensated_at" field.
func (u *EmptyResponseClaimUpsertBulk) ClearCompensatedAt() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.ClearCompensatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmptyResponseClaimUpsertBulk) SetUpdatedAt(v time.Time) *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmptyResponseClaimUpsertBulk) UpdateUpdatedAt() *EmptyResponseClaimUpsertBulk {
	return u.Update(func(s *EmptyResponseClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EmptyResponseClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmptyResponseClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmptyResponseClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmptyResponseClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
