// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryDrawUpdate is the builder for updating LotteryDraw entities.
type LotteryDrawUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryDrawMutation
}

// Where appends a list predicates to the LotteryDrawUpdate builder.
func (_u *LotteryDrawUpdate) Where(ps ...predicate.LotteryDraw) *LotteryDrawUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryDrawUpdate) SetActivityID(v int64) *LotteryDrawUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableActivityID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// ClearActivityID clears the value of the "activity_id" field.
func (_u *LotteryDrawUpdate) ClearActivityID() *LotteryDrawUpdate {
	_u.mutation.ClearActivityID()
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawUpdate) SetPrizeID(v int64) *LotteryDrawUpdate {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *LotteryDrawUpdate) ClearPrizeID() *LotteryDrawUpdate {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawUpdate) SetUserID(v int64) *LotteryDrawUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableUserID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawUpdate) AddUserID(v int64) *LotteryDrawUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawUpdate) SetPrizeName(v string) *LotteryDrawUpdate {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeName(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryDrawUpdate) SetPrizeType(v string) *LotteryDrawUpdate {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeType(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetBalanceAmount sets the "balance_amount" field.
func (_u *LotteryDrawUpdate) SetBalanceAmount(v float64) *LotteryDrawUpdate {
	_u.mutation.ResetBalanceAmount()
	_u.mutation.SetBalanceAmount(v)
	return _u
}

// SetNillableBalanceAmount sets the "balance_amount" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableBalanceAmount(v *float64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetBalanceAmount(*v)
	}
	return _u
}

// AddBalanceAmount adds value to the "balance_amount" field.
func (_u *LotteryDrawUpdate) AddBalanceAmount(v float64) *LotteryDrawUpdate {
	_u.mutation.AddBalanceAmount(v)
	return _u
}

// ClearBalanceAmount clears the value of the "balance_amount" field.
func (_u *LotteryDrawUpdate) ClearBalanceAmount() *LotteryDrawUpdate {
	_u.mutation.ClearBalanceAmount()
	return _u
}

// SetProductContent sets the "product_content" field.
func (_u *LotteryDrawUpdate) SetProductContent(v string) *LotteryDrawUpdate {
	_u.mutation.SetProductContent(v)
	return _u
}

// SetNillableProductContent sets the "product_content" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableProductContent(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetProductContent(*v)
	}
	return _u
}

// ClearProductContent clears the value of the "product_content" field.
func (_u *LotteryDrawUpdate) ClearProductContent() *LotteryDrawUpdate {
	_u.mutation.ClearProductContent()
	return _u
}

// SetAttemptKey sets the "attempt_key" field.
func (_u *LotteryDrawUpdate) SetAttemptKey(v string) *LotteryDrawUpdate {
	_u.mutation.SetAttemptKey(v)
	return _u
}

// SetNillableAttemptKey sets the "attempt_key" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableAttemptKey(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetAttemptKey(*v)
	}
	return _u
}

// SetAttemptSource sets the "attempt_source" field.
func (_u *LotteryDrawUpdate) SetAttemptSource(v string) *LotteryDrawUpdate {
	_u.mutation.SetAttemptSource(v)
	return _u
}

// SetNillableAttemptSource sets the "attempt_source" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableAttemptSource(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetAttemptSource(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryDrawUpdate) SetActivity(v *LotteryActivity) *LotteryDrawUpdate {
	return _u.SetActivityID(v.ID)
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawUpdate) SetPrize(v *LotteryPrize) *LotteryDrawUpdate {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the LotteryDrawMutation object of the builder.
func (_u *LotteryDrawUpdate) Mutation() *LotteryDrawMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryDrawUpdate) ClearActivity() *LotteryDrawUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// ClearPrize clears the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawUpdate) ClearPrize() *LotteryDrawUpdate {
	_u.mutation.ClearPrize()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryDrawUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryDrawUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawUpdate) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydraw.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotterydraw.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptKey(); ok {
		if err := lotterydraw.AttemptKeyValidator(v); err != nil {
			return &ValidationError{Name: "attempt_key", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.attempt_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptSource(); ok {
		if err := lotterydraw.AttemptSourceValidator(v); err != nil {
			return &ValidationError{Name: "attempt_source", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.attempt_source": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryDrawUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydraw.Table, lotterydraw.Columns, sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydraw.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotterydraw.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAmount(); ok {
		_spec.SetField(lotterydraw.FieldBalanceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAmount(); ok {
		_spec.AddField(lotterydraw.FieldBalanceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAmountCleared() {
		_spec.ClearField(lotterydraw.FieldBalanceAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductContent(); ok {
		_spec.SetField(lotterydraw.FieldProductContent, field.TypeString, value)
	}
	if _u.mutation.ProductContentCleared() {
		_spec.ClearField(lotterydraw.FieldProductContent, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptKey(); ok {
		_spec.SetField(lotterydraw.FieldAttemptKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptSource(); ok {
		_spec.SetField(lotterydraw.FieldAttemptSource, field.TypeString, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.ActivityTable,
			Columns: []string{lotterydraw.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.ActivityTable,
			Columns: []string{lotterydraw.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.PrizeTable,
			Columns: []string{lotterydraw.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.PrizeTable,
			Columns: []string{lotterydraw.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryDrawUpdateOne is the builder for updating a single LotteryDraw entity.
type LotteryDrawUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryDrawMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryDrawUpdateOne) SetActivityID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableActivityID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// ClearActivityID clears the value of the "activity_id" field.
func (_u *LotteryDrawUpdateOne) ClearActivityID() *LotteryDrawUpdateOne {
	_u.mutation.ClearActivityID()
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawUpdateOne) SetPrizeID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *LotteryDrawUpdateOne) ClearPrizeID() *LotteryDrawUpdateOne {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawUpdateOne) SetUserID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableUserID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawUpdateOne) AddUserID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawUpdateOne) SetPrizeName(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeName(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryDrawUpdateOne) SetPrizeType(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeType(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetBalanceAmount sets the "balance_amount" field.
func (_u *LotteryDrawUpdateOne) SetBalanceAmount(v float64) *LotteryDrawUpdateOne {
	_u.mutation.ResetBalanceAmount()
	_u.mutation.SetBalanceAmount(v)
	return _u
}

// SetNillableBalanceAmount sets the "balance_amount" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableBalanceAmount(v *float64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetBalanceAmount(*v)
	}
	return _u
}

// AddBalanceAmount adds value to the "balance_amount" field.
func (_u *LotteryDrawUpdateOne) AddBalanceAmount(v float64) *LotteryDrawUpdateOne {
	_u.mutation.AddBalanceAmount(v)
	return _u
}

// ClearBalanceAmount clears the value of the "balance_amount" field.
func (_u *LotteryDrawUpdateOne) ClearBalanceAmount() *LotteryDrawUpdateOne {
	_u.mutation.ClearBalanceAmount()
	return _u
}

// SetProductContent sets the "product_content" field.
func (_u *LotteryDrawUpdateOne) SetProductContent(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetProductContent(v)
	return _u
}

// SetNillableProductContent sets the "product_content" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableProductContent(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetProductContent(*v)
	}
	return _u
}

// ClearProductContent clears the value of the "product_content" field.
func (_u *LotteryDrawUpdateOne) ClearProductContent() *LotteryDrawUpdateOne {
	_u.mutation.ClearProductContent()
	return _u
}

// SetAttemptKey sets the "attempt_key" field.
func (_u *LotteryDrawUpdateOne) SetAttemptKey(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetAttemptKey(v)
	return _u
}

// SetNillableAttemptKey sets the "attempt_key" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableAttemptKey(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetAttemptKey(*v)
	}
	return _u
}

// SetAttemptSource sets the "attempt_source" field.
func (_u *LotteryDrawUpdateOne) SetAttemptSource(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetAttemptSource(v)
	return _u
}

// SetNillableAttemptSource sets the "attempt_source" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableAttemptSource(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetAttemptSource(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryDrawUpdateOne) SetActivity(v *LotteryActivity) *LotteryDrawUpdateOne {
	return _u.SetActivityID(v.ID)
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawUpdateOne) SetPrize(v *LotteryPrize) *LotteryDrawUpdateOne {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the LotteryDrawMutation object of the builder.
func (_u *LotteryDrawUpdateOne) Mutation() *LotteryDrawMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryDrawUpdateOne) ClearActivity() *LotteryDrawUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// ClearPrize clears the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawUpdateOne) ClearPrize() *LotteryDrawUpdateOne {
	_u.mutation.ClearPrize()
	return _u
}

// Where appends a list predicates to the LotteryDrawUpdate builder.
func (_u *LotteryDrawUpdateOne) Where(ps ...predicate.LotteryDraw) *LotteryDrawUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryDrawUpdateOne) Select(field string, fields ...string) *LotteryDrawUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryDraw entity.
func (_u *LotteryDrawUpdateOne) Save(ctx context.Context) (*LotteryDraw, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawUpdateOne) SaveX(ctx context.Context) *LotteryDraw {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryDrawUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawUpdateOne) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydraw.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotterydraw.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptKey(); ok {
		if err := lotterydraw.AttemptKeyValidator(v); err != nil {
			return &ValidationError{Name: "attempt_key", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.attempt_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptSource(); ok {
		if err := lotterydraw.AttemptSourceValidator(v); err != nil {
			return &ValidationError{Name: "attempt_source", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.attempt_source": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryDrawUpdateOne) sqlSave(ctx context.Context) (_node *LotteryDraw, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydraw.Table, lotterydraw.Columns, sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryDraw.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterydraw.FieldID)
		for _, f := range fields {
			if !lotterydraw.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterydraw.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydraw.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotterydraw.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAmount(); ok {
		_spec.SetField(lotterydraw.FieldBalanceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAmount(); ok {
		_spec.AddField(lotterydraw.FieldBalanceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAmountCleared() {
		_spec.ClearField(lotterydraw.FieldBalanceAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductContent(); ok {
		_spec.SetField(lotterydraw.FieldProductContent, field.TypeString, value)
	}
	if _u.mutation.ProductContentCleared() {
		_spec.ClearField(lotterydraw.FieldProductContent, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptKey(); ok {
		_spec.SetField(lotterydraw.FieldAttemptKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptSource(); ok {
		_spec.SetField(lotterydraw.FieldAttemptSource, field.TypeString, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.ActivityTable,
			Columns: []string{lotterydraw.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.ActivityTable,
			Columns: []string{lotterydraw.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.PrizeTable,
			Columns: []string{lotterydraw.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydraw.PrizeTable,
			Columns: []string{lotterydraw.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryDraw{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
