// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryattemptwallet"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryAttemptWalletUpdate is the builder for updating LotteryAttemptWallet entities.
type LotteryAttemptWalletUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryAttemptWalletMutation
}

// Where appends a list predicates to the LotteryAttemptWalletUpdate builder.
func (_u *LotteryAttemptWalletUpdate) Where(ps ...predicate.LotteryAttemptWallet) *LotteryAttemptWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryAttemptWalletUpdate) SetUserID(v int64) *LotteryAttemptWalletUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryAttemptWalletUpdate) SetNillableUserID(v *int64) *LotteryAttemptWalletUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *LotteryAttemptWalletUpdate) SetBalance(v int) *LotteryAttemptWalletUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *LotteryAttemptWalletUpdate) SetNillableBalance(v *int) *LotteryAttemptWalletUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *LotteryAttemptWalletUpdate) AddBalance(v int) *LotteryAttemptWalletUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryAttemptWalletUpdate) SetUpdatedAt(v time.Time) *LotteryAttemptWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryAttemptWalletUpdate) SetUser(v *User) *LotteryAttemptWalletUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the LotteryAttemptWalletMutation object of the builder.
func (_u *LotteryAttemptWalletUpdate) Mutation() *LotteryAttemptWalletMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryAttemptWalletUpdate) ClearUser() *LotteryAttemptWalletUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryAttemptWalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryAttemptWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryAttemptWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryAttemptWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryAttemptWalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryattemptwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryAttemptWalletUpdate) check() error {
	if v, ok := _u.mutation.Balance(); ok {
		if err := lotteryattemptwallet.BalanceValidator(v); err != nil {
			return &ValidationError{Name: "balance", err: fmt.Errorf(`ent: validator failed for field "LotteryAttemptWallet.balance": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryAttemptWallet.user"`)
	}
	return nil
}

func (_u *LotteryAttemptWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryattemptwallet.Table, lotteryattemptwallet.Columns, sqlgraph.NewFieldSpec(lotteryattemptwallet.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(lotteryattemptwallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(lotteryattemptwallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryattemptwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lotteryattemptwallet.UserTable,
			Columns: []string{lotteryattemptwallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lotteryattemptwallet.UserTable,
			Columns: []string{lotteryattemptwallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryattemptwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryAttemptWalletUpdateOne is the builder for updating a single LotteryAttemptWallet entity.
type LotteryAttemptWalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryAttemptWalletMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryAttemptWalletUpdateOne) SetUserID(v int64) *LotteryAttemptWalletUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryAttemptWalletUpdateOne) SetNillableUserID(v *int64) *LotteryAttemptWalletUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *LotteryAttemptWalletUpdateOne) SetBalance(v int) *LotteryAttemptWalletUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *LotteryAttemptWalletUpdateOne) SetNillableBalance(v *int) *LotteryAttemptWalletUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *LotteryAttemptWalletUpdateOne) AddBalance(v int) *LotteryAttemptWalletUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryAttemptWalletUpdateOne) SetUpdatedAt(v time.Time) *LotteryAttemptWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryAttemptWalletUpdateOne) SetUser(v *User) *LotteryAttemptWalletUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the LotteryAttemptWalletMutation object of the builder.
func (_u *LotteryAttemptWalletUpdateOne) Mutation() *LotteryAttemptWalletMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryAttemptWalletUpdateOne) ClearUser() *LotteryAttemptWalletUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the LotteryAttemptWalletUpdate builder.
func (_u *LotteryAttemptWalletUpdateOne) Where(ps ...predicate.LotteryAttemptWallet) *LotteryAttemptWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryAttemptWalletUpdateOne) Select(field string, fields ...string) *LotteryAttemptWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryAttemptWallet entity.
func (_u *LotteryAttemptWalletUpdateOne) Save(ctx context.Context) (*LotteryAttemptWallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryAttemptWalletUpdateOne) SaveX(ctx context.Context) *LotteryAttemptWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryAttemptWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryAttemptWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryAttemptWalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryattemptwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryAttemptWalletUpdateOne) check() error {
	if v, ok := _u.mutation.Balance(); ok {
		if err := lotteryattemptwallet.BalanceValidator(v); err != nil {
			return &ValidationError{Name: "balance", err: fmt.Errorf(`ent: validator failed for field "LotteryAttemptWallet.balance": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryAttemptWallet.user"`)
	}
	return nil
}

func (_u *LotteryAttemptWalletUpdateOne) sqlSave(ctx context.Context) (_node *LotteryAttemptWallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryattemptwallet.Table, lotteryattemptwallet.Columns, sqlgraph.NewFieldSpec(lotteryattemptwallet.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryAttemptWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryattemptwallet.FieldID)
		for _, f := range fields {
			if !lotteryattemptwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryattemptwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(lotteryattemptwallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(lotteryattemptwallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryattemptwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lotteryattemptwallet.UserTable,
			Columns: []string{lotteryattemptwallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lotteryattemptwallet.UserTable,
			Columns: []string{lotteryattemptwallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryAttemptWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryattemptwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
