// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprizeitem"
)

// LotteryPrizeItemCreate is the builder for creating a LotteryPrizeItem entity.
type LotteryPrizeItemCreate struct {
	config
	mutation *LotteryPrizeItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPrizeID sets the "prize_id" field.
func (_c *LotteryPrizeItemCreate) SetPrizeID(v int64) *LotteryPrizeItemCreate {
	_c.mutation.SetPrizeID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *LotteryPrizeItemCreate) SetContent(v string) *LotteryPrizeItemCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryPrizeItemCreate) SetStatus(v string) *LotteryPrizeItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryPrizeItemCreate) SetNillableStatus(v *string) *LotteryPrizeItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetClaimedBy sets the "claimed_by" field.
func (_c *LotteryPrizeItemCreate) SetClaimedBy(v int64) *LotteryPrizeItemCreate {
	_c.mutation.SetClaimedBy(v)
	return _c
}

// SetNillableClaimedBy sets the "claimed_by" field if the given value is not nil.
func (_c *LotteryPrizeItemCreate) SetNillableClaimedBy(v *int64) *LotteryPrizeItemCreate {
	if v != nil {
		_c.SetClaimedBy(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *LotteryPrizeItemCreate) SetClaimedAt(v time.Time) *LotteryPrizeItemCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *LotteryPrizeItemCreate) SetNillableClaimedAt(v *time.Time) *LotteryPrizeItemCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryPrizeItemCreate) SetCreatedAt(v time.Time) *LotteryPrizeItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryPrizeItemCreate) SetNillableCreatedAt(v *time.Time) *LotteryPrizeItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_c *LotteryPrizeItemCreate) SetPrize(v *LotteryPrize) *LotteryPrizeItemCreate {
	return _c.SetPrizeID(v.ID)
}

// Mutation returns the LotteryPrizeItemMutation object of the builder.
func (_c *LotteryPrizeItemCreate) Mutation() *LotteryPrizeItemMutation {
	return _c.mutation
}

// Save creates the LotteryPrizeItem in the database.
func (_c *LotteryPrizeItemCreate) Save(ctx context.Context) (*LotteryPrizeItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryPrizeItemCreate) SaveX(ctx context.Context) *LotteryPrizeItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizeItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizeItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryPrizeItemCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotteryprizeitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryprizeitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryPrizeItemCreate) check() error {
	if _, ok := _c.mutation.PrizeID(); !ok {
		return &ValidationError{Name: "prize_id", err: errors.New(`ent: missing required field "LotteryPrizeItem.prize_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "LotteryPrizeItem.content"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryPrizeItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotteryprizeitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryPrizeItem.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryPrizeItem.created_at"`)}
	}
	if len(_c.mutation.PrizeIDs()) == 0 {
		return &ValidationError{Name: "prize", err: errors.New(`ent: missing required edge "LotteryPrizeItem.prize"`)}
	}
	return nil
}

func (_c *LotteryPrizeItemCreate) sqlSave(ctx context.Context) (*LotteryPrizeItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryPrizeItemCreate) createSpec() (*LotteryPrizeItem, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryPrizeItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryprizeitem.Table, sqlgraph.NewFieldSpec(lotteryprizeitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(lotteryprizeitem.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotteryprizeitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ClaimedBy(); ok {
		_spec.SetField(lotteryprizeitem.FieldClaimedBy, field.TypeInt64, value)
		_node.ClaimedBy = &value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(lotteryprizeitem.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryprizeitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprizeitem.PrizeTable,
			Columns: []string{lotteryprizeitem.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrizeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrizeItem.Create().
//		SetPrizeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizeItemUpsert) {
//			SetPrizeID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizeItemCreate) OnConflict(opts ...sql.ConflictOption) *LotteryPrizeItemUpsertOne {
	_c.conflict = opts
	return &LotteryPrizeItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizeItemCreate) OnConflictColumns(columns ...string) *LotteryPrizeItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizeItemUpsertOne{
		create: _c,
	}
}

type (
	// LotteryPrizeItemUpsertOne is the builder for "upsert"-ing
	//  one LotteryPrizeItem node.
	LotteryPrizeItemUpsertOne struct {
		create *LotteryPrizeItemCreate
	}

	// LotteryPrizeItemUpsert is the "OnConflict" setter.
	LotteryPrizeItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetPrizeID sets the "prize_id" field.
func (u *LotteryPrizeItemUpsert) SetPrizeID(v int64) *LotteryPrizeItemUpsert {
	u.Set(lotteryprizeitem.FieldPrizeID, v)
	return u
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsert) UpdatePrizeID() *LotteryPrizeItemUpsert {
	u.SetExcluded(lotteryprizeitem.FieldPrizeID)
	return u
}

// SetContent sets the "content" field.
func (u *LotteryPrizeItemUpsert) SetContent(v string) *LotteryPrizeItemUpsert {
	u.Set(lotteryprizeitem.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsert) UpdateContent() *LotteryPrizeItemUpsert {
	u.SetExcluded(lotteryprizeitem.FieldContent)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryPrizeItemUpsert) SetStatus(v string) *LotteryPrizeItemUpsert {
	u.Set(lotteryprizeitem.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsert) UpdateStatus() *LotteryPrizeItemUpsert {
	u.SetExcluded(lotteryprizeitem.FieldStatus)
	return u
}

// SetClaimedBy sets the "claimed_by" field.
func (u *LotteryPrizeItemUpsert) SetClaimedBy(v int64) *LotteryPrizeItemUpsert {
	u.Set(lotteryprizeitem.FieldClaimedBy, v)
	return u
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsert) UpdateClaimedBy() *LotteryPrizeItemUpsert {
	u.SetExcluded(lotteryprizeitem.FieldClaimedBy)
	return u
}

// AddClaimedBy adds v to the "claimed_by" field.
func (u *LotteryPrizeItemUpsert) AddClaimedBy(v int64) *LotteryPrizeItemUpsert {
	u.Add(lotteryprizeitem.FieldClaimedBy, v)
	return u
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *LotteryPrizeItemUpsert) ClearClaimedBy() *LotteryPrizeItemUpsert {
	u.SetNull(lotteryprizeitem.FieldClaimedBy)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *LotteryPrizeItemUpsert) SetClaimedAt(v time.Time) *LotteryPrizeItemUpsert {
	u.Set(lotteryprizeitem.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsert) UpdateClaimedAt() *LotteryPrizeItemUpsert {
	u.SetExcluded(lotteryprizeitem.FieldClaimedAt)
	return u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *LotteryPrizeItemUpsert) ClearClaimedAt() *LotteryPrizeItemUpsert {
	u.SetNull(lotteryprizeitem.FieldClaimedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizeItemUpsertOne) UpdateNewValues() *LotteryPrizeItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryprizeitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryPrizeItemUpsertOne) Ignore() *LotteryPrizeItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizeItemUpsertOne) DoNothing() *LotteryPrizeItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizeItemCreate.OnConflict
// documentation for more info.
func (u *LotteryPrizeItemUpsertOne) Update(set func(*LotteryPrizeItemUpsert)) *LotteryPrizeItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizeItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryPrizeItemUpsertOne) SetPrizeID(v int64) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertOne) UpdatePrizeID() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdatePrizeID()
	})
}

// SetContent sets the "content" field.
func (u *LotteryPrizeItemUpsertOne) SetContent(v string) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertOne) UpdateContent() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryPrizeItemUpsertOne) SetStatus(v string) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertOne) UpdateStatus() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateStatus()
	})
}

// SetClaimedBy sets the "claimed_by" field.
func (u *LotteryPrizeItemUpsertOne) SetClaimedBy(v int64) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetClaimedBy(v)
	})
}

// AddClaimedBy adds v to the "claimed_by" field.
func (u *LotteryPrizeItemUpsertOne) AddClaimedBy(v int64) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.AddClaimedBy(v)
	})
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertOne) UpdateClaimedBy() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateClaimedBy()
	})
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *LotteryPrizeItemUpsertOne) ClearClaimedBy() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.ClearClaimedBy()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *LotteryPrizeItemUpsertOne) SetClaimedAt(v time.Time) *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertOne) UpdateClaimedAt() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *LotteryPrizeItemUpsertOne) ClearClaimedAt() *LotteryPrizeItemUpsertOne {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.ClearClaimedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizeItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizeItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizeItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryPrizeItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryPrizeItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryPrizeItemCreateBulk is the builder for creating many LotteryPrizeItem entities in bulk.
type LotteryPrizeItemCreateBulk struct {
	config
	err      error
	builders []*LotteryPrizeItemCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryPrizeItem entities in the database.
func (_c *LotteryPrizeItemCreateBulk) Save(ctx context.Context) ([]*LotteryPrizeItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryPrizeItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryPrizeItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryPrizeItemCreateBulk) SaveX(ctx context.Context) []*LotteryPrizeItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizeItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizeItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrizeItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizeItemUpsert) {
//			SetPrizeID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizeItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryPrizeItemUpsertBulk {
	_c.conflict = opts
	return &LotteryPrizeItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizeItemCreateBulk) OnConflictColumns(columns ...string) *LotteryPrizeItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizeItemUpsertBulk{
		create: _c,
	}
}

// LotteryPrizeItemUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryPrizeItem nodes.
type LotteryPrizeItemUpsertBulk struct {
	create *LotteryPrizeItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizeItemUpsertBulk) UpdateNewValues() *LotteryPrizeItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryprizeitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrizeItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryPrizeItemUpsertBulk) Ignore() *LotteryPrizeItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizeItemUpsertBulk) DoNothing() *LotteryPrizeItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizeItemCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryPrizeItemUpsertBulk) Update(set func(*LotteryPrizeItemUpsert)) *LotteryPrizeItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizeItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryPrizeItemUpsertBulk) SetPrizeID(v int64) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertBulk) UpdatePrizeID() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdatePrizeID()
	})
}

// SetContent sets the "content" field.
func (u *LotteryPrizeItemUpsertBulk) SetContent(v string) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertBulk) UpdateContent() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryPrizeItemUpsertBulk) SetStatus(v string) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertBulk) UpdateStatus() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateStatus()
	})
}

// SetClaimedBy sets the "claimed_by" field.
func (u *LotteryPrizeItemUpsertBulk) SetClaimedBy(v int64) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetClaimedBy(v)
	})
}

// AddClaimedBy adds v to the "claimed_by" field.
func (u *LotteryPrizeItemUpsertBulk) AddClaimedBy(v int64) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.AddClaimedBy(v)
	})
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertBulk) UpdateClaimedBy() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateClaimedBy()
	})
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *LotteryPrizeItemUpsertBulk) ClearClaimedBy() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.ClearClaimedBy()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *LotteryPrizeItemUpsertBulk) SetClaimedAt(v time.Time) *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *LotteryPrizeItemUpsertBulk) UpdateClaimedAt() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *LotteryPrizeItemUpsertBulk) ClearClaimedAt() *LotteryPrizeItemUpsertBulk {
	return u.Update(func(s *LotteryPrizeItemUpsert) {
		s.ClearClaimedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizeItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryPrizeItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizeItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizeItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
