// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subadmincommissiongrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubAdminCommissionGrantUpdate is the builder for updating SubAdminCommissionGrant entities.
type SubAdminCommissionGrantUpdate struct {
	config
	hooks    []Hook
	mutation *SubAdminCommissionGrantMutation
}

// Where appends a list predicates to the SubAdminCommissionGrantUpdate builder.
func (_u *SubAdminCommissionGrantUpdate) Where(ps ...predicate.SubAdminCommissionGrant) *SubAdminCommissionGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubAdminUserID sets the "sub_admin_user_id" field.
func (_u *SubAdminCommissionGrantUpdate) SetSubAdminUserID(v int64) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetSubAdminUserID(v)
	return _u
}

// SetNillableSubAdminUserID sets the "sub_admin_user_id" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableSubAdminUserID(v *int64) *SubAdminCommissionGrantUpdate {
	if v != nil {
		_u.SetSubAdminUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubAdminCommissionGrantUpdate) SetGroupID(v int64) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableGroupID(v *int64) *SubAdminCommissionGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGrantedDate sets the "granted_date" field.
func (_u *SubAdminCommissionGrantUpdate) SetGrantedDate(v time.Time) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetGrantedDate(v)
	return _u
}

// SetNillableGrantedDate sets the "granted_date" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableGrantedDate(v *time.Time) *SubAdminCommissionGrantUpdate {
	if v != nil {
		_u.SetGrantedDate(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubAdminCommissionGrantUpdate) SetEnabled(v bool) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableEnabled(v *bool) *SubAdminCommissionGrantUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SubAdminCommissionGrantUpdate) SetCreatedBy(v int64) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableCreatedBy(v *int64) *SubAdminCommissionGrantUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SubAdminCommissionGrantUpdate) ClearCreatedBy() *SubAdminCommissionGrantUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubAdminCommissionGrantUpdate) SetUpdatedAt(v time.Time) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubAdminID sets the "sub_admin" edge to the User entity by ID.
func (_u *SubAdminCommissionGrantUpdate) SetSubAdminID(id int64) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetSubAdminID(id)
	return _u
}

// SetSubAdmin sets the "sub_admin" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdate) SetSubAdmin(v *User) *SubAdminCommissionGrantUpdate {
	return _u.SetSubAdminID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubAdminCommissionGrantUpdate) SetGroup(v *Group) *SubAdminCommissionGrantUpdate {
	return _u.SetGroupID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *SubAdminCommissionGrantUpdate) SetCreatorID(id int64) *SubAdminCommissionGrantUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdate) SetNillableCreatorID(id *int64) *SubAdminCommissionGrantUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdate) SetCreator(v *User) *SubAdminCommissionGrantUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the SubAdminCommissionGrantMutation object of the builder.
func (_u *SubAdminCommissionGrantUpdate) Mutation() *SubAdminCommissionGrantMutation {
	return _u.mutation
}

// ClearSubAdmin clears the "sub_admin" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdate) ClearSubAdmin() *SubAdminCommissionGrantUpdate {
	_u.mutation.ClearSubAdmin()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubAdminCommissionGrantUpdate) ClearGroup() *SubAdminCommissionGrantUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdate) ClearCreator() *SubAdminCommissionGrantUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubAdminCommissionGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubAdminCommissionGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubAdminCommissionGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubAdminCommissionGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubAdminCommissionGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subadmincommissiongrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubAdminCommissionGrantUpdate) check() error {
	if _u.mutation.SubAdminCleared() && len(_u.mutation.SubAdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAdminCommissionGrant.sub_admin"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAdminCommissionGrant.group"`)
	}
	return nil
}

func (_u *SubAdminCommissionGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subadmincommissiongrant.Table, subadmincommissiongrant.Columns, sqlgraph.NewFieldSpec(subadmincommissiongrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GrantedDate(); ok {
		_spec.SetField(subadmincommissiongrant.FieldGrantedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subadmincommissiongrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subadmincommissiongrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.SubAdminTable,
			Columns: []string{subadmincommissiongrant.SubAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.SubAdminTable,
			Columns: []string{subadmincommissiongrant.SubAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.GroupTable,
			Columns: []string{subadmincommissiongrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.GroupTable,
			Columns: []string{subadmincommissiongrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.CreatorTable,
			Columns: []string{subadmincommissiongrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.CreatorTable,
			Columns: []string{subadmincommissiongrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subadmincommissiongrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubAdminCommissionGrantUpdateOne is the builder for updating a single SubAdminCommissionGrant entity.
type SubAdminCommissionGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubAdminCommissionGrantMutation
}

// SetSubAdminUserID sets the "sub_admin_user_id" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetSubAdminUserID(v int64) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetSubAdminUserID(v)
	return _u
}

// SetNillableSubAdminUserID sets the "sub_admin_user_id" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableSubAdminUserID(v *int64) *SubAdminCommissionGrantUpdateOne {
	if v != nil {
		_u.SetSubAdminUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetGroupID(v int64) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableGroupID(v *int64) *SubAdminCommissionGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGrantedDate sets the "granted_date" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetGrantedDate(v time.Time) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetGrantedDate(v)
	return _u
}

// SetNillableGrantedDate sets the "granted_date" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableGrantedDate(v *time.Time) *SubAdminCommissionGrantUpdateOne {
	if v != nil {
		_u.SetGrantedDate(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetEnabled(v bool) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableEnabled(v *bool) *SubAdminCommissionGrantUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetCreatedBy(v int64) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableCreatedBy(v *int64) *SubAdminCommissionGrantUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SubAdminCommissionGrantUpdateOne) ClearCreatedBy() *SubAdminCommissionGrantUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubAdminCommissionGrantUpdateOne) SetUpdatedAt(v time.Time) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubAdminID sets the "sub_admin" edge to the User entity by ID.
func (_u *SubAdminCommissionGrantUpdateOne) SetSubAdminID(id int64) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetSubAdminID(id)
	return _u
}

// SetSubAdmin sets the "sub_admin" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdateOne) SetSubAdmin(v *User) *SubAdminCommissionGrantUpdateOne {
	return _u.SetSubAdminID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubAdminCommissionGrantUpdateOne) SetGroup(v *Group) *SubAdminCommissionGrantUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *SubAdminCommissionGrantUpdateOne) SetCreatorID(id int64) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *SubAdminCommissionGrantUpdateOne) SetNillableCreatorID(id *int64) *SubAdminCommissionGrantUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdateOne) SetCreator(v *User) *SubAdminCommissionGrantUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the SubAdminCommissionGrantMutation object of the builder.
func (_u *SubAdminCommissionGrantUpdateOne) Mutation() *SubAdminCommissionGrantMutation {
	return _u.mutation
}

// ClearSubAdmin clears the "sub_admin" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdateOne) ClearSubAdmin() *SubAdminCommissionGrantUpdateOne {
	_u.mutation.ClearSubAdmin()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubAdminCommissionGrantUpdateOne) ClearGroup() *SubAdminCommissionGrantUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *SubAdminCommissionGrantUpdateOne) ClearCreator() *SubAdminCommissionGrantUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the SubAdminCommissionGrantUpdate builder.
func (_u *SubAdminCommissionGrantUpdateOne) Where(ps ...predicate.SubAdminCommissionGrant) *SubAdminCommissionGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubAdminCommissionGrantUpdateOne) Select(field string, fields ...string) *SubAdminCommissionGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubAdminCommissionGrant entity.
func (_u *SubAdminCommissionGrantUpdateOne) Save(ctx context.Context) (*SubAdminCommissionGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubAdminCommissionGrantUpdateOne) SaveX(ctx context.Context) *SubAdminCommissionGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubAdminCommissionGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubAdminCommissionGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubAdminCommissionGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subadmincommissiongrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubAdminCommissionGrantUpdateOne) check() error {
	if _u.mutation.SubAdminCleared() && len(_u.mutation.SubAdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAdminCommissionGrant.sub_admin"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAdminCommissionGrant.group"`)
	}
	return nil
}

func (_u *SubAdminCommissionGrantUpdateOne) sqlSave(ctx context.Context) (_node *SubAdminCommissionGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subadmincommissiongrant.Table, subadmincommissiongrant.Columns, sqlgraph.NewFieldSpec(subadmincommissiongrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubAdminCommissionGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subadmincommissiongrant.FieldID)
		for _, f := range fields {
			if !subadmincommissiongrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subadmincommissiongrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GrantedDate(); ok {
		_spec.SetField(subadmincommissiongrant.FieldGrantedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subadmincommissiongrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subadmincommissiongrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.SubAdminTable,
			Columns: []string{subadmincommissiongrant.SubAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.SubAdminTable,
			Columns: []string{subadmincommissiongrant.SubAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.GroupTable,
			Columns: []string{subadmincommissiongrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.GroupTable,
			Columns: []string{subadmincommissiongrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.CreatorTable,
			Columns: []string{subadmincommissiongrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subadmincommissiongrant.CreatorTable,
			Columns: []string{subadmincommissiongrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubAdminCommissionGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subadmincommissiongrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
