// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/systemcustomgroupmodel"
)

// SystemCustomGroupModelUpdate is the builder for updating SystemCustomGroupModel entities.
type SystemCustomGroupModelUpdate struct {
	config
	hooks    []Hook
	mutation *SystemCustomGroupModelMutation
}

// Where appends a list predicates to the SystemCustomGroupModelUpdate builder.
func (_u *SystemCustomGroupModelUpdate) Where(ps ...predicate.SystemCustomGroupModel) *SystemCustomGroupModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SystemCustomGroupModelUpdate) SetGroupID(v int64) *SystemCustomGroupModelUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdate) SetNillableGroupID(v *int64) *SystemCustomGroupModelUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *SystemCustomGroupModelUpdate) SetPublicModel(v string) *SystemCustomGroupModelUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdate) SetNillablePublicModel(v *string) *SystemCustomGroupModelUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetSourceGroupID sets the "source_group_id" field.
func (_u *SystemCustomGroupModelUpdate) SetSourceGroupID(v int64) *SystemCustomGroupModelUpdate {
	_u.mutation.SetSourceGroupID(v)
	return _u
}

// SetNillableSourceGroupID sets the "source_group_id" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdate) SetNillableSourceGroupID(v *int64) *SystemCustomGroupModelUpdate {
	if v != nil {
		_u.SetSourceGroupID(*v)
	}
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *SystemCustomGroupModelUpdate) SetSourceModel(v string) *SystemCustomGroupModelUpdate {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdate) SetNillableSourceModel(v *string) *SystemCustomGroupModelUpdate {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SystemCustomGroupModelUpdate) SetEnabled(v bool) *SystemCustomGroupModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdate) SetNillableEnabled(v *bool) *SystemCustomGroupModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemCustomGroupModelUpdate) SetUpdatedAt(v time.Time) *SystemCustomGroupModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdate) SetGroup(v *Group) *SystemCustomGroupModelUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSourceGroup sets the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdate) SetSourceGroup(v *Group) *SystemCustomGroupModelUpdate {
	return _u.SetSourceGroupID(v.ID)
}

// Mutation returns the SystemCustomGroupModelMutation object of the builder.
func (_u *SystemCustomGroupModelUpdate) Mutation() *SystemCustomGroupModelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdate) ClearGroup() *SystemCustomGroupModelUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSourceGroup clears the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdate) ClearSourceGroup() *SystemCustomGroupModelUpdate {
	_u.mutation.ClearSourceGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemCustomGroupModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemCustomGroupModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemCustomGroupModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemCustomGroupModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemCustomGroupModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemcustomgroupmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemCustomGroupModelUpdate) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := systemcustomgroupmodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceModel(); ok {
		if err := systemcustomgroupmodel.SourceModelValidator(v); err != nil {
			return &ValidationError{Name: "source_model", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupModel.source_model": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupModel.group"`)
	}
	if _u.mutation.SourceGroupCleared() && len(_u.mutation.SourceGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupModel.source_group"`)
	}
	return nil
}

func (_u *SystemCustomGroupModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemcustomgroupmodel.Table, systemcustomgroupmodel.Columns, sqlgraph.NewFieldSpec(systemcustomgroupmodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldSourceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.GroupTable,
			Columns: []string{systemcustomgroupmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.GroupTable,
			Columns: []string{systemcustomgroupmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.SourceGroupTable,
			Columns: []string{systemcustomgroupmodel.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.SourceGroupTable,
			Columns: []string{systemcustomgroupmodel.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemcustomgroupmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemCustomGroupModelUpdateOne is the builder for updating a single SystemCustomGroupModel entity.
type SystemCustomGroupModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemCustomGroupModelMutation
}

// SetGroupID sets the "group_id" field.
func (_u *SystemCustomGroupModelUpdateOne) SetGroupID(v int64) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdateOne) SetNillableGroupID(v *int64) *SystemCustomGroupModelUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *SystemCustomGroupModelUpdateOne) SetPublicModel(v string) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdateOne) SetNillablePublicModel(v *string) *SystemCustomGroupModelUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetSourceGroupID sets the "source_group_id" field.
func (_u *SystemCustomGroupModelUpdateOne) SetSourceGroupID(v int64) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetSourceGroupID(v)
	return _u
}

// SetNillableSourceGroupID sets the "source_group_id" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdateOne) SetNillableSourceGroupID(v *int64) *SystemCustomGroupModelUpdateOne {
	if v != nil {
		_u.SetSourceGroupID(*v)
	}
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *SystemCustomGroupModelUpdateOne) SetSourceModel(v string) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdateOne) SetNillableSourceModel(v *string) *SystemCustomGroupModelUpdateOne {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SystemCustomGroupModelUpdateOne) SetEnabled(v bool) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SystemCustomGroupModelUpdateOne) SetNillableEnabled(v *bool) *SystemCustomGroupModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemCustomGroupModelUpdateOne) SetUpdatedAt(v time.Time) *SystemCustomGroupModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdateOne) SetGroup(v *Group) *SystemCustomGroupModelUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSourceGroup sets the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdateOne) SetSourceGroup(v *Group) *SystemCustomGroupModelUpdateOne {
	return _u.SetSourceGroupID(v.ID)
}

// Mutation returns the SystemCustomGroupModelMutation object of the builder.
func (_u *SystemCustomGroupModelUpdateOne) Mutation() *SystemCustomGroupModelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdateOne) ClearGroup() *SystemCustomGroupModelUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSourceGroup clears the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupModelUpdateOne) ClearSourceGroup() *SystemCustomGroupModelUpdateOne {
	_u.mutation.ClearSourceGroup()
	return _u
}

// Where appends a list predicates to the SystemCustomGroupModelUpdate builder.
func (_u *SystemCustomGroupModelUpdateOne) Where(ps ...predicate.SystemCustomGroupModel) *SystemCustomGroupModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemCustomGroupModelUpdateOne) Select(field string, fields ...string) *SystemCustomGroupModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemCustomGroupModel entity.
func (_u *SystemCustomGroupModelUpdateOne) Save(ctx context.Context) (*SystemCustomGroupModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemCustomGroupModelUpdateOne) SaveX(ctx context.Context) *SystemCustomGroupModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemCustomGroupModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemCustomGroupModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemCustomGroupModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemcustomgroupmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemCustomGroupModelUpdateOne) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := systemcustomgroupmodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceModel(); ok {
		if err := systemcustomgroupmodel.SourceModelValidator(v); err != nil {
			return &ValidationError{Name: "source_model", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupModel.source_model": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupModel.group"`)
	}
	if _u.mutation.SourceGroupCleared() && len(_u.mutation.SourceGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupModel.source_group"`)
	}
	return nil
}

func (_u *SystemCustomGroupModelUpdateOne) sqlSave(ctx context.Context) (_node *SystemCustomGroupModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemcustomgroupmodel.Table, systemcustomgroupmodel.Columns, sqlgraph.NewFieldSpec(systemcustomgroupmodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemCustomGroupModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemcustomgroupmodel.FieldID)
		for _, f := range fields {
			if !systemcustomgroupmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemcustomgroupmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldSourceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemcustomgroupmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.GroupTable,
			Columns: []string{systemcustomgroupmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.GroupTable,
			Columns: []string{systemcustomgroupmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.SourceGroupTable,
			Columns: []string{systemcustomgroupmodel.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupmodel.SourceGroupTable,
			Columns: []string{systemcustomgroupmodel.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemCustomGroupModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemcustomgroupmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
