// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/systemcustomgroupsource"
)

// SystemCustomGroupSourceUpdate is the builder for updating SystemCustomGroupSource entities.
type SystemCustomGroupSourceUpdate struct {
	config
	hooks    []Hook
	mutation *SystemCustomGroupSourceMutation
}

// Where appends a list predicates to the SystemCustomGroupSourceUpdate builder.
func (_u *SystemCustomGroupSourceUpdate) Where(ps ...predicate.SystemCustomGroupSource) *SystemCustomGroupSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SystemCustomGroupSourceUpdate) SetGroupID(v int64) *SystemCustomGroupSourceUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdate) SetNillableGroupID(v *int64) *SystemCustomGroupSourceUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSourceGroupID sets the "source_group_id" field.
func (_u *SystemCustomGroupSourceUpdate) SetSourceGroupID(v int64) *SystemCustomGroupSourceUpdate {
	_u.mutation.SetSourceGroupID(v)
	return _u
}

// SetNillableSourceGroupID sets the "source_group_id" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdate) SetNillableSourceGroupID(v *int64) *SystemCustomGroupSourceUpdate {
	if v != nil {
		_u.SetSourceGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SystemCustomGroupSourceUpdate) SetPriority(v int) *SystemCustomGroupSourceUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdate) SetNillablePriority(v *int) *SystemCustomGroupSourceUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *SystemCustomGroupSourceUpdate) AddPriority(v int) *SystemCustomGroupSourceUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemCustomGroupSourceUpdate) SetUpdatedAt(v time.Time) *SystemCustomGroupSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdate) SetGroup(v *Group) *SystemCustomGroupSourceUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSourceGroup sets the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdate) SetSourceGroup(v *Group) *SystemCustomGroupSourceUpdate {
	return _u.SetSourceGroupID(v.ID)
}

// Mutation returns the SystemCustomGroupSourceMutation object of the builder.
func (_u *SystemCustomGroupSourceUpdate) Mutation() *SystemCustomGroupSourceMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdate) ClearGroup() *SystemCustomGroupSourceUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSourceGroup clears the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdate) ClearSourceGroup() *SystemCustomGroupSourceUpdate {
	_u.mutation.ClearSourceGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemCustomGroupSourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemCustomGroupSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemCustomGroupSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemCustomGroupSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemCustomGroupSourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemcustomgroupsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemCustomGroupSourceUpdate) check() error {
	if v, ok := _u.mutation.Priority(); ok {
		if err := systemcustomgroupsource.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupSource.priority": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupSource.group"`)
	}
	if _u.mutation.SourceGroupCleared() && len(_u.mutation.SourceGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupSource.source_group"`)
	}
	return nil
}

func (_u *SystemCustomGroupSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemcustomgroupsource.Table, systemcustomgroupsource.Columns, sqlgraph.NewFieldSpec(systemcustomgroupsource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(systemcustomgroupsource.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(systemcustomgroupsource.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemcustomgroupsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.GroupTable,
			Columns: []string{systemcustomgroupsource.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.GroupTable,
			Columns: []string{systemcustomgroupsource.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.SourceGroupTable,
			Columns: []string{systemcustomgroupsource.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.SourceGroupTable,
			Columns: []string{systemcustomgroupsource.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemcustomgroupsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemCustomGroupSourceUpdateOne is the builder for updating a single SystemCustomGroupSource entity.
type SystemCustomGroupSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemCustomGroupSourceMutation
}

// SetGroupID sets the "group_id" field.
func (_u *SystemCustomGroupSourceUpdateOne) SetGroupID(v int64) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdateOne) SetNillableGroupID(v *int64) *SystemCustomGroupSourceUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSourceGroupID sets the "source_group_id" field.
func (_u *SystemCustomGroupSourceUpdateOne) SetSourceGroupID(v int64) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.SetSourceGroupID(v)
	return _u
}

// SetNillableSourceGroupID sets the "source_group_id" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdateOne) SetNillableSourceGroupID(v *int64) *SystemCustomGroupSourceUpdateOne {
	if v != nil {
		_u.SetSourceGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SystemCustomGroupSourceUpdateOne) SetPriority(v int) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SystemCustomGroupSourceUpdateOne) SetNillablePriority(v *int) *SystemCustomGroupSourceUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *SystemCustomGroupSourceUpdateOne) AddPriority(v int) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemCustomGroupSourceUpdateOne) SetUpdatedAt(v time.Time) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdateOne) SetGroup(v *Group) *SystemCustomGroupSourceUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSourceGroup sets the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdateOne) SetSourceGroup(v *Group) *SystemCustomGroupSourceUpdateOne {
	return _u.SetSourceGroupID(v.ID)
}

// Mutation returns the SystemCustomGroupSourceMutation object of the builder.
func (_u *SystemCustomGroupSourceUpdateOne) Mutation() *SystemCustomGroupSourceMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdateOne) ClearGroup() *SystemCustomGroupSourceUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSourceGroup clears the "source_group" edge to the Group entity.
func (_u *SystemCustomGroupSourceUpdateOne) ClearSourceGroup() *SystemCustomGroupSourceUpdateOne {
	_u.mutation.ClearSourceGroup()
	return _u
}

// Where appends a list predicates to the SystemCustomGroupSourceUpdate builder.
func (_u *SystemCustomGroupSourceUpdateOne) Where(ps ...predicate.SystemCustomGroupSource) *SystemCustomGroupSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemCustomGroupSourceUpdateOne) Select(field string, fields ...string) *SystemCustomGroupSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemCustomGroupSource entity.
func (_u *SystemCustomGroupSourceUpdateOne) Save(ctx context.Context) (*SystemCustomGroupSource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemCustomGroupSourceUpdateOne) SaveX(ctx context.Context) *SystemCustomGroupSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemCustomGroupSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemCustomGroupSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemCustomGroupSourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemcustomgroupsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemCustomGroupSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Priority(); ok {
		if err := systemcustomgroupsource.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SystemCustomGroupSource.priority": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupSource.group"`)
	}
	if _u.mutation.SourceGroupCleared() && len(_u.mutation.SourceGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemCustomGroupSource.source_group"`)
	}
	return nil
}

func (_u *SystemCustomGroupSourceUpdateOne) sqlSave(ctx context.Context) (_node *SystemCustomGroupSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemcustomgroupsource.Table, systemcustomgroupsource.Columns, sqlgraph.NewFieldSpec(systemcustomgroupsource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemCustomGroupSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemcustomgroupsource.FieldID)
		for _, f := range fields {
			if !systemcustomgroupsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemcustomgroupsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(systemcustomgroupsource.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(systemcustomgroupsource.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemcustomgroupsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.GroupTable,
			Columns: []string{systemcustomgroupsource.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.GroupTable,
			Columns: []string{systemcustomgroupsource.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.SourceGroupTable,
			Columns: []string{systemcustomgroupsource.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemcustomgroupsource.SourceGroupTable,
			Columns: []string{systemcustomgroupsource.SourceGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemCustomGroupSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemcustomgroupsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
