// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/systemcustomgroupsource"
)

// SystemCustomGroupSource is the model entity for the SystemCustomGroupSource schema.
type SystemCustomGroupSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// SourceGroupID holds the value of the "source_group_id" field.
	SourceGroupID int64 `json:"source_group_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SystemCustomGroupSourceQuery when eager-loading is set.
	Edges        SystemCustomGroupSourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SystemCustomGroupSourceEdges holds the relations/edges for other nodes in the graph.
type SystemCustomGroupSourceEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// SourceGroup holds the value of the source_group edge.
	SourceGroup *Group `json:"source_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemCustomGroupSourceEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// SourceGroupOrErr returns the SourceGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemCustomGroupSourceEdges) SourceGroupOrErr() (*Group, error) {
	if e.SourceGroup != nil {
		return e.SourceGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "source_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemCustomGroupSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemcustomgroupsource.FieldID, systemcustomgroupsource.FieldGroupID, systemcustomgroupsource.FieldSourceGroupID, systemcustomgroupsource.FieldPriority:
			values[i] = new(sql.NullInt64)
		case systemcustomgroupsource.FieldCreatedAt, systemcustomgroupsource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemCustomGroupSource fields.
func (_m *SystemCustomGroupSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemcustomgroupsource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case systemcustomgroupsource.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case systemcustomgroupsource.FieldSourceGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_group_id", values[i])
			} else if value.Valid {
				_m.SourceGroupID = value.Int64
			}
		case systemcustomgroupsource.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case systemcustomgroupsource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case systemcustomgroupsource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemCustomGroupSource.
// This includes values selected through modifiers, order, etc.
func (_m *SystemCustomGroupSource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the SystemCustomGroupSource entity.
func (_m *SystemCustomGroupSource) QueryGroup() *GroupQuery {
	return NewSystemCustomGroupSourceClient(_m.config).QueryGroup(_m)
}

// QuerySourceGroup queries the "source_group" edge of the SystemCustomGroupSource entity.
func (_m *SystemCustomGroupSource) QuerySourceGroup() *GroupQuery {
	return NewSystemCustomGroupSourceClient(_m.config).QuerySourceGroup(_m)
}

// Update returns a builder for updating this SystemCustomGroupSource.
// Note that you need to call SystemCustomGroupSource.Unwrap() before calling this method if this SystemCustomGroupSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemCustomGroupSource) Update() *SystemCustomGroupSourceUpdateOne {
	return NewSystemCustomGroupSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemCustomGroupSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemCustomGroupSource) Unwrap() *SystemCustomGroupSource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemCustomGroupSource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemCustomGroupSource) String() string {
	var builder strings.Builder
	builder.WriteString("SystemCustomGroupSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("source_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceGroupID))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SystemCustomGroupSources is a parsable slice of SystemCustomGroupSource.
type SystemCustomGroupSources []*SystemCustomGroupSource
