// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usageresponseoutcome"
)

// UsageResponseOutcome is the model entity for the UsageResponseOutcome schema.
type UsageResponseOutcome struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus int `json:"http_status,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus int `json:"upstream_status,omitempty"`
	// HasText holds the value of the "has_text" field.
	HasText bool `json:"has_text,omitempty"`
	// HasToolCall holds the value of the "has_tool_call" field.
	HasToolCall bool `json:"has_tool_call,omitempty"`
	// HasReasoning holds the value of the "has_reasoning" field.
	HasReasoning bool `json:"has_reasoning,omitempty"`
	// HasMedia holds the value of the "has_media" field.
	HasMedia bool `json:"has_media,omitempty"`
	// OutputBytes holds the value of the "output_bytes" field.
	OutputBytes int64 `json:"output_bytes,omitempty"`
	// EventCount holds the value of the "event_count" field.
	EventCount int `json:"event_count,omitempty"`
	// StreamCompleted holds the value of the "stream_completed" field.
	StreamCompleted bool `json:"stream_completed,omitempty"`
	// FinishReason holds the value of the "finish_reason" field.
	FinishReason string `json:"finish_reason,omitempty"`
	// DisconnectSource holds the value of the "disconnect_source" field.
	DisconnectSource string `json:"disconnect_source,omitempty"`
	// UpstreamErrorKind holds the value of the "upstream_error_kind" field.
	UpstreamErrorKind string `json:"upstream_error_kind,omitempty"`
	// CollectorVersion holds the value of the "collector_version" field.
	CollectorVersion int16 `json:"collector_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageResponseOutcome) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usageresponseoutcome.FieldHasText, usageresponseoutcome.FieldHasToolCall, usageresponseoutcome.FieldHasReasoning, usageresponseoutcome.FieldHasMedia, usageresponseoutcome.FieldStreamCompleted:
			values[i] = new(sql.NullBool)
		case usageresponseoutcome.FieldID, usageresponseoutcome.FieldUsageLogID, usageresponseoutcome.FieldAPIKeyID, usageresponseoutcome.FieldUserID, usageresponseoutcome.FieldAccountID, usageresponseoutcome.FieldGroupID, usageresponseoutcome.FieldHTTPStatus, usageresponseoutcome.FieldUpstreamStatus, usageresponseoutcome.FieldOutputBytes, usageresponseoutcome.FieldEventCount, usageresponseoutcome.FieldCollectorVersion:
			values[i] = new(sql.NullInt64)
		case usageresponseoutcome.FieldRequestID, usageresponseoutcome.FieldFinishReason, usageresponseoutcome.FieldDisconnectSource, usageresponseoutcome.FieldUpstreamErrorKind:
			values[i] = new(sql.NullString)
		case usageresponseoutcome.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageResponseOutcome fields.
func (_m *UsageResponseOutcome) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usageresponseoutcome.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usageresponseoutcome.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case usageresponseoutcome.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usageresponseoutcome.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case usageresponseoutcome.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usageresponseoutcome.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usageresponseoutcome.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case usageresponseoutcome.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = int(value.Int64)
			}
		case usageresponseoutcome.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = int(value.Int64)
			}
		case usageresponseoutcome.FieldHasText:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_text", values[i])
			} else if value.Valid {
				_m.HasText = value.Bool
			}
		case usageresponseoutcome.FieldHasToolCall:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_tool_call", values[i])
			} else if value.Valid {
				_m.HasToolCall = value.Bool
			}
		case usageresponseoutcome.FieldHasReasoning:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_reasoning", values[i])
			} else if value.Valid {
				_m.HasReasoning = value.Bool
			}
		case usageresponseoutcome.FieldHasMedia:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_media", values[i])
			} else if value.Valid {
				_m.HasMedia = value.Bool
			}
		case usageresponseoutcome.FieldOutputBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_bytes", values[i])
			} else if value.Valid {
				_m.OutputBytes = value.Int64
			}
		case usageresponseoutcome.FieldEventCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_count", values[i])
			} else if value.Valid {
				_m.EventCount = int(value.Int64)
			}
		case usageresponseoutcome.FieldStreamCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream_completed", values[i])
			} else if value.Valid {
				_m.StreamCompleted = value.Bool
			}
		case usageresponseoutcome.FieldFinishReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field finish_reason", values[i])
			} else if value.Valid {
				_m.FinishReason = value.String
			}
		case usageresponseoutcome.FieldDisconnectSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disconnect_source", values[i])
			} else if value.Valid {
				_m.DisconnectSource = value.String
			}
		case usageresponseoutcome.FieldUpstreamErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_error_kind", values[i])
			} else if value.Valid {
				_m.UpstreamErrorKind = value.String
			}
		case usageresponseoutcome.FieldCollectorVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field collector_version", values[i])
			} else if value.Valid {
				_m.CollectorVersion = int16(value.Int64)
			}
		case usageresponseoutcome.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageResponseOutcome.
// This includes values selected through modifiers, order, etc.
func (_m *UsageResponseOutcome) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageResponseOutcome.
// Note that you need to call UsageResponseOutcome.Unwrap() before calling this method if this UsageResponseOutcome
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageResponseOutcome) Update() *UsageResponseOutcomeUpdateOne {
	return NewUsageResponseOutcomeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageResponseOutcome entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageResponseOutcome) Unwrap() *UsageResponseOutcome {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageResponseOutcome is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageResponseOutcome) String() string {
	var builder strings.Builder
	builder.WriteString("UsageResponseOutcome(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("http_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPStatus))
	builder.WriteString(", ")
	builder.WriteString("upstream_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamStatus))
	builder.WriteString(", ")
	builder.WriteString("has_text=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasText))
	builder.WriteString(", ")
	builder.WriteString("has_tool_call=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasToolCall))
	builder.WriteString(", ")
	builder.WriteString("has_reasoning=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasReasoning))
	builder.WriteString(", ")
	builder.WriteString("has_media=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasMedia))
	builder.WriteString(", ")
	builder.WriteString("output_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputBytes))
	builder.WriteString(", ")
	builder.WriteString("event_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventCount))
	builder.WriteString(", ")
	builder.WriteString("stream_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreamCompleted))
	builder.WriteString(", ")
	builder.WriteString("finish_reason=")
	builder.WriteString(_m.FinishReason)
	builder.WriteString(", ")
	builder.WriteString("disconnect_source=")
	builder.WriteString(_m.DisconnectSource)
	builder.WriteString(", ")
	builder.WriteString("upstream_error_kind=")
	builder.WriteString(_m.UpstreamErrorKind)
	builder.WriteString(", ")
	builder.WriteString("collector_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectorVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageResponseOutcomes is a parsable slice of UsageResponseOutcome.
type UsageResponseOutcomes []*UsageResponseOutcome
