// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercheckinstatussnapshot"
)

// UserCheckinStatusSnapshotUpdate is the builder for updating UserCheckinStatusSnapshot entities.
type UserCheckinStatusSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *UserCheckinStatusSnapshotMutation
}

// Where appends a list predicates to the UserCheckinStatusSnapshotUpdate builder.
func (_u *UserCheckinStatusSnapshotUpdate) Where(ps ...predicate.UserCheckinStatusSnapshot) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCheckinStatusSnapshotUpdate) SetUpdatedAt(v time.Time) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserCheckinStatusSnapshotUpdate) SetUserID(v int64) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdate) SetNillableUserID(v *int64) *UserCheckinStatusSnapshotUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrentStreak sets the "current_streak" field.
func (_u *UserCheckinStatusSnapshotUpdate) SetCurrentStreak(v int) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.ResetCurrentStreak()
	_u.mutation.SetCurrentStreak(v)
	return _u
}

// SetNillableCurrentStreak sets the "current_streak" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdate) SetNillableCurrentStreak(v *int) *UserCheckinStatusSnapshotUpdate {
	if v != nil {
		_u.SetCurrentStreak(*v)
	}
	return _u
}

// AddCurrentStreak adds value to the "current_streak" field.
func (_u *UserCheckinStatusSnapshotUpdate) AddCurrentStreak(v int) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.AddCurrentStreak(v)
	return _u
}

// SetLastCheckinDate sets the "last_checkin_date" field.
func (_u *UserCheckinStatusSnapshotUpdate) SetLastCheckinDate(v string) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.SetLastCheckinDate(v)
	return _u
}

// SetNillableLastCheckinDate sets the "last_checkin_date" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdate) SetNillableLastCheckinDate(v *string) *UserCheckinStatusSnapshotUpdate {
	if v != nil {
		_u.SetLastCheckinDate(*v)
	}
	return _u
}

// SetLifetimeCheckinDays sets the "lifetime_checkin_days" field.
func (_u *UserCheckinStatusSnapshotUpdate) SetLifetimeCheckinDays(v int) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.ResetLifetimeCheckinDays()
	_u.mutation.SetLifetimeCheckinDays(v)
	return _u
}

// SetNillableLifetimeCheckinDays sets the "lifetime_checkin_days" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdate) SetNillableLifetimeCheckinDays(v *int) *UserCheckinStatusSnapshotUpdate {
	if v != nil {
		_u.SetLifetimeCheckinDays(*v)
	}
	return _u
}

// AddLifetimeCheckinDays adds value to the "lifetime_checkin_days" field.
func (_u *UserCheckinStatusSnapshotUpdate) AddLifetimeCheckinDays(v int) *UserCheckinStatusSnapshotUpdate {
	_u.mutation.AddLifetimeCheckinDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserCheckinStatusSnapshotUpdate) SetUser(v *User) *UserCheckinStatusSnapshotUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserCheckinStatusSnapshotMutation object of the builder.
func (_u *UserCheckinStatusSnapshotUpdate) Mutation() *UserCheckinStatusSnapshotMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserCheckinStatusSnapshotUpdate) ClearUser() *UserCheckinStatusSnapshotUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserCheckinStatusSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCheckinStatusSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserCheckinStatusSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCheckinStatusSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserCheckinStatusSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercheckinstatussnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCheckinStatusSnapshotUpdate) check() error {
	if v, ok := _u.mutation.LastCheckinDate(); ok {
		if err := usercheckinstatussnapshot.LastCheckinDateValidator(v); err != nil {
			return &ValidationError{Name: "last_checkin_date", err: fmt.Errorf(`ent: validator failed for field "UserCheckinStatusSnapshot.last_checkin_date": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCheckinStatusSnapshot.user"`)
	}
	return nil
}

func (_u *UserCheckinStatusSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercheckinstatussnapshot.Table, usercheckinstatussnapshot.Columns, sqlgraph.NewFieldSpec(usercheckinstatussnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentStreak(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStreak(); ok {
		_spec.AddField(usercheckinstatussnapshot.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckinDate(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldLastCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeCheckinDays(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldLifetimeCheckinDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeCheckinDays(); ok {
		_spec.AddField(usercheckinstatussnapshot.FieldLifetimeCheckinDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercheckinstatussnapshot.UserTable,
			Columns: []string{usercheckinstatussnapshot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercheckinstatussnapshot.UserTable,
			Columns: []string{usercheckinstatussnapshot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercheckinstatussnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserCheckinStatusSnapshotUpdateOne is the builder for updating a single UserCheckinStatusSnapshot entity.
type UserCheckinStatusSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserCheckinStatusSnapshotMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetUpdatedAt(v time.Time) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetUserID(v int64) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetNillableUserID(v *int64) *UserCheckinStatusSnapshotUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrentStreak sets the "current_streak" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetCurrentStreak(v int) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.ResetCurrentStreak()
	_u.mutation.SetCurrentStreak(v)
	return _u
}

// SetNillableCurrentStreak sets the "current_streak" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetNillableCurrentStreak(v *int) *UserCheckinStatusSnapshotUpdateOne {
	if v != nil {
		_u.SetCurrentStreak(*v)
	}
	return _u
}

// AddCurrentStreak adds value to the "current_streak" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) AddCurrentStreak(v int) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.AddCurrentStreak(v)
	return _u
}

// SetLastCheckinDate sets the "last_checkin_date" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetLastCheckinDate(v string) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.SetLastCheckinDate(v)
	return _u
}

// SetNillableLastCheckinDate sets the "last_checkin_date" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetNillableLastCheckinDate(v *string) *UserCheckinStatusSnapshotUpdateOne {
	if v != nil {
		_u.SetLastCheckinDate(*v)
	}
	return _u
}

// SetLifetimeCheckinDays sets the "lifetime_checkin_days" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetLifetimeCheckinDays(v int) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.ResetLifetimeCheckinDays()
	_u.mutation.SetLifetimeCheckinDays(v)
	return _u
}

// SetNillableLifetimeCheckinDays sets the "lifetime_checkin_days" field if the given value is not nil.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetNillableLifetimeCheckinDays(v *int) *UserCheckinStatusSnapshotUpdateOne {
	if v != nil {
		_u.SetLifetimeCheckinDays(*v)
	}
	return _u
}

// AddLifetimeCheckinDays adds value to the "lifetime_checkin_days" field.
func (_u *UserCheckinStatusSnapshotUpdateOne) AddLifetimeCheckinDays(v int) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.AddLifetimeCheckinDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserCheckinStatusSnapshotUpdateOne) SetUser(v *User) *UserCheckinStatusSnapshotUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserCheckinStatusSnapshotMutation object of the builder.
func (_u *UserCheckinStatusSnapshotUpdateOne) Mutation() *UserCheckinStatusSnapshotMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserCheckinStatusSnapshotUpdateOne) ClearUser() *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserCheckinStatusSnapshotUpdate builder.
func (_u *UserCheckinStatusSnapshotUpdateOne) Where(ps ...predicate.UserCheckinStatusSnapshot) *UserCheckinStatusSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserCheckinStatusSnapshotUpdateOne) Select(field string, fields ...string) *UserCheckinStatusSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserCheckinStatusSnapshot entity.
func (_u *UserCheckinStatusSnapshotUpdateOne) Save(ctx context.Context) (*UserCheckinStatusSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCheckinStatusSnapshotUpdateOne) SaveX(ctx context.Context) *UserCheckinStatusSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserCheckinStatusSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCheckinStatusSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserCheckinStatusSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercheckinstatussnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCheckinStatusSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.LastCheckinDate(); ok {
		if err := usercheckinstatussnapshot.LastCheckinDateValidator(v); err != nil {
			return &ValidationError{Name: "last_checkin_date", err: fmt.Errorf(`ent: validator failed for field "UserCheckinStatusSnapshot.last_checkin_date": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCheckinStatusSnapshot.user"`)
	}
	return nil
}

func (_u *UserCheckinStatusSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *UserCheckinStatusSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercheckinstatussnapshot.Table, usercheckinstatussnapshot.Columns, sqlgraph.NewFieldSpec(usercheckinstatussnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserCheckinStatusSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercheckinstatussnapshot.FieldID)
		for _, f := range fields {
			if !usercheckinstatussnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usercheckinstatussnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentStreak(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStreak(); ok {
		_spec.AddField(usercheckinstatussnapshot.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckinDate(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldLastCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeCheckinDays(); ok {
		_spec.SetField(usercheckinstatussnapshot.FieldLifetimeCheckinDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeCheckinDays(); ok {
		_spec.AddField(usercheckinstatussnapshot.FieldLifetimeCheckinDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercheckinstatussnapshot.UserTable,
			Columns: []string{usercheckinstatussnapshot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercheckinstatussnapshot.UserTable,
			Columns: []string{usercheckinstatussnapshot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserCheckinStatusSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercheckinstatussnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
