// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercheckinblacklist"
)

// UserCheckinBlacklist is the model entity for the UserCheckinBlacklist schema.
type UserCheckinBlacklist struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// RemovedBy holds the value of the "removed_by" field.
	RemovedBy *int64 `json:"removed_by,omitempty"`
	// RemovedAt holds the value of the "removed_at" field.
	RemovedAt *time.Time `json:"removed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCheckinBlacklistQuery when eager-loading is set.
	Edges        UserCheckinBlacklistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCheckinBlacklistEdges holds the relations/edges for other nodes in the graph.
type UserCheckinBlacklistEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCheckinBlacklistEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCheckinBlacklist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercheckinblacklist.FieldID, usercheckinblacklist.FieldUserID, usercheckinblacklist.FieldCreatedBy, usercheckinblacklist.FieldRemovedBy:
			values[i] = new(sql.NullInt64)
		case usercheckinblacklist.FieldReason:
			values[i] = new(sql.NullString)
		case usercheckinblacklist.FieldCreatedAt, usercheckinblacklist.FieldUpdatedAt, usercheckinblacklist.FieldRemovedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCheckinBlacklist fields.
func (_m *UserCheckinBlacklist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercheckinblacklist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usercheckinblacklist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usercheckinblacklist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usercheckinblacklist.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usercheckinblacklist.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case usercheckinblacklist.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case usercheckinblacklist.FieldRemovedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field removed_by", values[i])
			} else if value.Valid {
				_m.RemovedBy = new(int64)
				*_m.RemovedBy = value.Int64
			}
		case usercheckinblacklist.FieldRemovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field removed_at", values[i])
			} else if value.Valid {
				_m.RemovedAt = new(time.Time)
				*_m.RemovedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCheckinBlacklist.
// This includes values selected through modifiers, order, etc.
func (_m *UserCheckinBlacklist) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserCheckinBlacklist entity.
func (_m *UserCheckinBlacklist) QueryUser() *UserQuery {
	return NewUserCheckinBlacklistClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserCheckinBlacklist.
// Note that you need to call UserCheckinBlacklist.Unwrap() before calling this method if this UserCheckinBlacklist
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCheckinBlacklist) Update() *UserCheckinBlacklistUpdateOne {
	return NewUserCheckinBlacklistClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCheckinBlacklist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCheckinBlacklist) Unwrap() *UserCheckinBlacklist {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCheckinBlacklist is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCheckinBlacklist) String() string {
	var builder strings.Builder
	builder.WriteString("UserCheckinBlacklist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RemovedBy; v != nil {
		builder.WriteString("removed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RemovedAt; v != nil {
		builder.WriteString("removed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserCheckinBlacklists is a parsable slice of UserCheckinBlacklist.
type UserCheckinBlacklists []*UserCheckinBlacklist
