// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usercustomgroup"
	"github.com/Wei-Shaw/sub2api/ent/usercustomgroupmodel"
)

// UserCustomGroupModel is the model entity for the UserCustomGroupModel schema.
type UserCustomGroupModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CustomGroupID holds the value of the "custom_group_id" field.
	CustomGroupID int64 `json:"custom_group_id,omitempty"`
	// PublicModel holds the value of the "public_model" field.
	PublicModel string `json:"public_model,omitempty"`
	// SourceGroupID holds the value of the "source_group_id" field.
	SourceGroupID int64 `json:"source_group_id,omitempty"`
	// SourceModel holds the value of the "source_model" field.
	SourceModel string `json:"source_model,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCustomGroupModelQuery when eager-loading is set.
	Edges        UserCustomGroupModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCustomGroupModelEdges holds the relations/edges for other nodes in the graph.
type UserCustomGroupModelEdges struct {
	// CustomGroup holds the value of the custom_group edge.
	CustomGroup *UserCustomGroup `json:"custom_group,omitempty"`
	// SourceGroup holds the value of the source_group edge.
	SourceGroup *Group `json:"source_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CustomGroupOrErr returns the CustomGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCustomGroupModelEdges) CustomGroupOrErr() (*UserCustomGroup, error) {
	if e.CustomGroup != nil {
		return e.CustomGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usercustomgroup.Label}
	}
	return nil, &NotLoadedError{edge: "custom_group"}
}

// SourceGroupOrErr returns the SourceGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCustomGroupModelEdges) SourceGroupOrErr() (*Group, error) {
	if e.SourceGroup != nil {
		return e.SourceGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "source_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCustomGroupModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercustomgroupmodel.FieldID, usercustomgroupmodel.FieldCustomGroupID, usercustomgroupmodel.FieldSourceGroupID:
			values[i] = new(sql.NullInt64)
		case usercustomgroupmodel.FieldPublicModel, usercustomgroupmodel.FieldSourceModel:
			values[i] = new(sql.NullString)
		case usercustomgroupmodel.FieldCreatedAt, usercustomgroupmodel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCustomGroupModel fields.
func (_m *UserCustomGroupModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercustomgroupmodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usercustomgroupmodel.FieldCustomGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field custom_group_id", values[i])
			} else if value.Valid {
				_m.CustomGroupID = value.Int64
			}
		case usercustomgroupmodel.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case usercustomgroupmodel.FieldSourceGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_group_id", values[i])
			} else if value.Valid {
				_m.SourceGroupID = value.Int64
			}
		case usercustomgroupmodel.FieldSourceModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_model", values[i])
			} else if value.Valid {
				_m.SourceModel = value.String
			}
		case usercustomgroupmodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usercustomgroupmodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCustomGroupModel.
// This includes values selected through modifiers, order, etc.
func (_m *UserCustomGroupModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCustomGroup queries the "custom_group" edge of the UserCustomGroupModel entity.
func (_m *UserCustomGroupModel) QueryCustomGroup() *UserCustomGroupQuery {
	return NewUserCustomGroupModelClient(_m.config).QueryCustomGroup(_m)
}

// QuerySourceGroup queries the "source_group" edge of the UserCustomGroupModel entity.
func (_m *UserCustomGroupModel) QuerySourceGroup() *GroupQuery {
	return NewUserCustomGroupModelClient(_m.config).QuerySourceGroup(_m)
}

// Update returns a builder for updating this UserCustomGroupModel.
// Note that you need to call UserCustomGroupModel.Unwrap() before calling this method if this UserCustomGroupModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCustomGroupModel) Update() *UserCustomGroupModelUpdateOne {
	return NewUserCustomGroupModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCustomGroupModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCustomGroupModel) Unwrap() *UserCustomGroupModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCustomGroupModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCustomGroupModel) String() string {
	var builder strings.Builder
	builder.WriteString("UserCustomGroupModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("custom_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomGroupID))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("source_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceGroupID))
	builder.WriteString(", ")
	builder.WriteString("source_model=")
	builder.WriteString(_m.SourceModel)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCustomGroupModels is a parsable slice of UserCustomGroupModel.
type UserCustomGroupModels []*UserCustomGroupModel
