// Code generated by ent, DO NOT EDIT.

package usercheckinstatussnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usercheckinstatussnapshot type in the database.
	Label = "user_checkin_status_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCurrentStreak holds the string denoting the current_streak field in the database.
	FieldCurrentStreak = "current_streak"
	// FieldLastCheckinDate holds the string denoting the last_checkin_date field in the database.
	FieldLastCheckinDate = "last_checkin_date"
	// FieldLifetimeCheckinDays holds the string denoting the lifetime_checkin_days field in the database.
	FieldLifetimeCheckinDays = "lifetime_checkin_days"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the usercheckinstatussnapshot in the database.
	Table = "user_checkin_status_snapshots"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_checkin_status_snapshots"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for usercheckinstatussnapshot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCurrentStreak,
	FieldLastCheckinDate,
	FieldLifetimeCheckinDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCurrentStreak holds the default value on creation for the "current_streak" field.
	DefaultCurrentStreak int
	// LastCheckinDateValidator is a validator for the "last_checkin_date" field. It is called by the builders before save.
	LastCheckinDateValidator func(string) error
	// DefaultLifetimeCheckinDays holds the default value on creation for the "lifetime_checkin_days" field.
	DefaultLifetimeCheckinDays int
)

// OrderOption defines the ordering options for the UserCheckinStatusSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCurrentStreak orders the results by the current_streak field.
func ByCurrentStreak(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStreak, opts...).ToFunc()
}

// ByLastCheckinDate orders the results by the last_checkin_date field.
func ByLastCheckinDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckinDate, opts...).ToFunc()
}

// ByLifetimeCheckinDays orders the results by the lifetime_checkin_days field.
func ByLifetimeCheckinDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeCheckinDays, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
