// Code generated by ent, DO NOT EDIT.

package usageresponseoutcome

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageresponseoutcome type in the database.
	Label = "usage_response_outcome"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldHasText holds the string denoting the has_text field in the database.
	FieldHasText = "has_text"
	// FieldHasToolCall holds the string denoting the has_tool_call field in the database.
	FieldHasToolCall = "has_tool_call"
	// FieldHasReasoning holds the string denoting the has_reasoning field in the database.
	FieldHasReasoning = "has_reasoning"
	// FieldHasMedia holds the string denoting the has_media field in the database.
	FieldHasMedia = "has_media"
	// FieldOutputBytes holds the string denoting the output_bytes field in the database.
	FieldOutputBytes = "output_bytes"
	// FieldEventCount holds the string denoting the event_count field in the database.
	FieldEventCount = "event_count"
	// FieldStreamCompleted holds the string denoting the stream_completed field in the database.
	FieldStreamCompleted = "stream_completed"
	// FieldFinishReason holds the string denoting the finish_reason field in the database.
	FieldFinishReason = "finish_reason"
	// FieldDisconnectSource holds the string denoting the disconnect_source field in the database.
	FieldDisconnectSource = "disconnect_source"
	// FieldUpstreamErrorKind holds the string denoting the upstream_error_kind field in the database.
	FieldUpstreamErrorKind = "upstream_error_kind"
	// FieldCollectorVersion holds the string denoting the collector_version field in the database.
	FieldCollectorVersion = "collector_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the usageresponseoutcome in the database.
	Table = "usage_response_outcomes"
)

// Columns holds all SQL columns for usageresponseoutcome fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldRequestID,
	FieldAPIKeyID,
	FieldUserID,
	FieldAccountID,
	FieldGroupID,
	FieldHTTPStatus,
	FieldUpstreamStatus,
	FieldHasText,
	FieldHasToolCall,
	FieldHasReasoning,
	FieldHasMedia,
	FieldOutputBytes,
	FieldEventCount,
	FieldStreamCompleted,
	FieldFinishReason,
	FieldDisconnectSource,
	FieldUpstreamErrorKind,
	FieldCollectorVersion,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultHTTPStatus holds the default value on creation for the "http_status" field.
	DefaultHTTPStatus int
	// DefaultUpstreamStatus holds the default value on creation for the "upstream_status" field.
	DefaultUpstreamStatus int
	// DefaultHasText holds the default value on creation for the "has_text" field.
	DefaultHasText bool
	// DefaultHasToolCall holds the default value on creation for the "has_tool_call" field.
	DefaultHasToolCall bool
	// DefaultHasReasoning holds the default value on creation for the "has_reasoning" field.
	DefaultHasReasoning bool
	// DefaultHasMedia holds the default value on creation for the "has_media" field.
	DefaultHasMedia bool
	// DefaultOutputBytes holds the default value on creation for the "output_bytes" field.
	DefaultOutputBytes int64
	// DefaultEventCount holds the default value on creation for the "event_count" field.
	DefaultEventCount int
	// DefaultStreamCompleted holds the default value on creation for the "stream_completed" field.
	DefaultStreamCompleted bool
	// DefaultFinishReason holds the default value on creation for the "finish_reason" field.
	DefaultFinishReason string
	// FinishReasonValidator is a validator for the "finish_reason" field. It is called by the builders before save.
	FinishReasonValidator func(string) error
	// DefaultDisconnectSource holds the default value on creation for the "disconnect_source" field.
	DefaultDisconnectSource string
	// DisconnectSourceValidator is a validator for the "disconnect_source" field. It is called by the builders before save.
	DisconnectSourceValidator func(string) error
	// DefaultUpstreamErrorKind holds the default value on creation for the "upstream_error_kind" field.
	DefaultUpstreamErrorKind string
	// UpstreamErrorKindValidator is a validator for the "upstream_error_kind" field. It is called by the builders before save.
	UpstreamErrorKindValidator func(string) error
	// DefaultCollectorVersion holds the default value on creation for the "collector_version" field.
	DefaultCollectorVersion int16
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageResponseOutcome queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByHasText orders the results by the has_text field.
func ByHasText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasText, opts...).ToFunc()
}

// ByHasToolCall orders the results by the has_tool_call field.
func ByHasToolCall(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasToolCall, opts...).ToFunc()
}

// ByHasReasoning orders the results by the has_reasoning field.
func ByHasReasoning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasReasoning, opts...).ToFunc()
}

// ByHasMedia orders the results by the has_media field.
func ByHasMedia(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasMedia, opts...).ToFunc()
}

// ByOutputBytes orders the results by the output_bytes field.
func ByOutputBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputBytes, opts...).ToFunc()
}

// ByEventCount orders the results by the event_count field.
func ByEventCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventCount, opts...).ToFunc()
}

// ByStreamCompleted orders the results by the stream_completed field.
func ByStreamCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamCompleted, opts...).ToFunc()
}

// ByFinishReason orders the results by the finish_reason field.
func ByFinishReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishReason, opts...).ToFunc()
}

// ByDisconnectSource orders the results by the disconnect_source field.
func ByDisconnectSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisconnectSource, opts...).ToFunc()
}

// ByUpstreamErrorKind orders the results by the upstream_error_kind field.
func ByUpstreamErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamErrorKind, opts...).ToFunc()
}

// ByCollectorVersion orders the results by the collector_version field.
func ByCollectorVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectorVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
