// Code generated by ent, DO NOT EDIT.

package usageresponseoutcome

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldGroupID, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHTTPStatus, v))
}

// UpstreamStatus applies equality check predicate on the "upstream_status" field. It's identical to UpstreamStatusEQ.
func UpstreamStatus(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUpstreamStatus, v))
}

// HasText applies equality check predicate on the "has_text" field. It's identical to HasTextEQ.
func HasText(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasText, v))
}

// HasToolCall applies equality check predicate on the "has_tool_call" field. It's identical to HasToolCallEQ.
func HasToolCall(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasToolCall, v))
}

// HasReasoning applies equality check predicate on the "has_reasoning" field. It's identical to HasReasoningEQ.
func HasReasoning(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasReasoning, v))
}

// HasMedia applies equality check predicate on the "has_media" field. It's identical to HasMediaEQ.
func HasMedia(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasMedia, v))
}

// OutputBytes applies equality check predicate on the "output_bytes" field. It's identical to OutputBytesEQ.
func OutputBytes(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldOutputBytes, v))
}

// EventCount applies equality check predicate on the "event_count" field. It's identical to EventCountEQ.
func EventCount(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldEventCount, v))
}

// StreamCompleted applies equality check predicate on the "stream_completed" field. It's identical to StreamCompletedEQ.
func StreamCompleted(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldStreamCompleted, v))
}

// FinishReason applies equality check predicate on the "finish_reason" field. It's identical to FinishReasonEQ.
func FinishReason(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldFinishReason, v))
}

// DisconnectSource applies equality check predicate on the "disconnect_source" field. It's identical to DisconnectSourceEQ.
func DisconnectSource(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldDisconnectSource, v))
}

// UpstreamErrorKind applies equality check predicate on the "upstream_error_kind" field. It's identical to UpstreamErrorKindEQ.
func UpstreamErrorKind(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUpstreamErrorKind, v))
}

// CollectorVersion applies equality check predicate on the "collector_version" field. It's identical to CollectorVersionEQ.
func CollectorVersion(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldCollectorVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotNull(FieldUsageLogID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContainsFold(FieldRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldAPIKeyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldAccountID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotNull(FieldGroupID))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldHTTPStatus, v))
}

// UpstreamStatusEQ applies the EQ predicate on the "upstream_status" field.
func UpstreamStatusEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusNEQ applies the NEQ predicate on the "upstream_status" field.
func UpstreamStatusNEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusIn applies the In predicate on the "upstream_status" field.
func UpstreamStatusIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusNotIn applies the NotIn predicate on the "upstream_status" field.
func UpstreamStatusNotIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusGT applies the GT predicate on the "upstream_status" field.
func UpstreamStatusGT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldUpstreamStatus, v))
}

// UpstreamStatusGTE applies the GTE predicate on the "upstream_status" field.
func UpstreamStatusGTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldUpstreamStatus, v))
}

// UpstreamStatusLT applies the LT predicate on the "upstream_status" field.
func UpstreamStatusLT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldUpstreamStatus, v))
}

// UpstreamStatusLTE applies the LTE predicate on the "upstream_status" field.
func UpstreamStatusLTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldUpstreamStatus, v))
}

// HasTextEQ applies the EQ predicate on the "has_text" field.
func HasTextEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasText, v))
}

// HasTextNEQ applies the NEQ predicate on the "has_text" field.
func HasTextNEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldHasText, v))
}

// HasToolCallEQ applies the EQ predicate on the "has_tool_call" field.
func HasToolCallEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasToolCall, v))
}

// HasToolCallNEQ applies the NEQ predicate on the "has_tool_call" field.
func HasToolCallNEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldHasToolCall, v))
}

// HasReasoningEQ applies the EQ predicate on the "has_reasoning" field.
func HasReasoningEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasReasoning, v))
}

// HasReasoningNEQ applies the NEQ predicate on the "has_reasoning" field.
func HasReasoningNEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldHasReasoning, v))
}

// HasMediaEQ applies the EQ predicate on the "has_media" field.
func HasMediaEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldHasMedia, v))
}

// HasMediaNEQ applies the NEQ predicate on the "has_media" field.
func HasMediaNEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldHasMedia, v))
}

// OutputBytesEQ applies the EQ predicate on the "output_bytes" field.
func OutputBytesEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldOutputBytes, v))
}

// OutputBytesNEQ applies the NEQ predicate on the "output_bytes" field.
func OutputBytesNEQ(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldOutputBytes, v))
}

// OutputBytesIn applies the In predicate on the "output_bytes" field.
func OutputBytesIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldOutputBytes, vs...))
}

// OutputBytesNotIn applies the NotIn predicate on the "output_bytes" field.
func OutputBytesNotIn(vs ...int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldOutputBytes, vs...))
}

// OutputBytesGT applies the GT predicate on the "output_bytes" field.
func OutputBytesGT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldOutputBytes, v))
}

// OutputBytesGTE applies the GTE predicate on the "output_bytes" field.
func OutputBytesGTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldOutputBytes, v))
}

// OutputBytesLT applies the LT predicate on the "output_bytes" field.
func OutputBytesLT(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldOutputBytes, v))
}

// OutputBytesLTE applies the LTE predicate on the "output_bytes" field.
func OutputBytesLTE(v int64) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldOutputBytes, v))
}

// EventCountEQ applies the EQ predicate on the "event_count" field.
func EventCountEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldEventCount, v))
}

// EventCountNEQ applies the NEQ predicate on the "event_count" field.
func EventCountNEQ(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldEventCount, v))
}

// EventCountIn applies the In predicate on the "event_count" field.
func EventCountIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldEventCount, vs...))
}

// EventCountNotIn applies the NotIn predicate on the "event_count" field.
func EventCountNotIn(vs ...int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldEventCount, vs...))
}

// EventCountGT applies the GT predicate on the "event_count" field.
func EventCountGT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldEventCount, v))
}

// EventCountGTE applies the GTE predicate on the "event_count" field.
func EventCountGTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldEventCount, v))
}

// EventCountLT applies the LT predicate on the "event_count" field.
func EventCountLT(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldEventCount, v))
}

// EventCountLTE applies the LTE predicate on the "event_count" field.
func EventCountLTE(v int) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldEventCount, v))
}

// StreamCompletedEQ applies the EQ predicate on the "stream_completed" field.
func StreamCompletedEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldStreamCompleted, v))
}

// StreamCompletedNEQ applies the NEQ predicate on the "stream_completed" field.
func StreamCompletedNEQ(v bool) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldStreamCompleted, v))
}

// FinishReasonEQ applies the EQ predicate on the "finish_reason" field.
func FinishReasonEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldFinishReason, v))
}

// FinishReasonNEQ applies the NEQ predicate on the "finish_reason" field.
func FinishReasonNEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldFinishReason, v))
}

// FinishReasonIn applies the In predicate on the "finish_reason" field.
func FinishReasonIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldFinishReason, vs...))
}

// FinishReasonNotIn applies the NotIn predicate on the "finish_reason" field.
func FinishReasonNotIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldFinishReason, vs...))
}

// FinishReasonGT applies the GT predicate on the "finish_reason" field.
func FinishReasonGT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldFinishReason, v))
}

// FinishReasonGTE applies the GTE predicate on the "finish_reason" field.
func FinishReasonGTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldFinishReason, v))
}

// FinishReasonLT applies the LT predicate on the "finish_reason" field.
func FinishReasonLT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldFinishReason, v))
}

// FinishReasonLTE applies the LTE predicate on the "finish_reason" field.
func FinishReasonLTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldFinishReason, v))
}

// FinishReasonContains applies the Contains predicate on the "finish_reason" field.
func FinishReasonContains(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContains(FieldFinishReason, v))
}

// FinishReasonHasPrefix applies the HasPrefix predicate on the "finish_reason" field.
func FinishReasonHasPrefix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasPrefix(FieldFinishReason, v))
}

// FinishReasonHasSuffix applies the HasSuffix predicate on the "finish_reason" field.
func FinishReasonHasSuffix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasSuffix(FieldFinishReason, v))
}

// FinishReasonEqualFold applies the EqualFold predicate on the "finish_reason" field.
func FinishReasonEqualFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEqualFold(FieldFinishReason, v))
}

// FinishReasonContainsFold applies the ContainsFold predicate on the "finish_reason" field.
func FinishReasonContainsFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContainsFold(FieldFinishReason, v))
}

// DisconnectSourceEQ applies the EQ predicate on the "disconnect_source" field.
func DisconnectSourceEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldDisconnectSource, v))
}

// DisconnectSourceNEQ applies the NEQ predicate on the "disconnect_source" field.
func DisconnectSourceNEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldDisconnectSource, v))
}

// DisconnectSourceIn applies the In predicate on the "disconnect_source" field.
func DisconnectSourceIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldDisconnectSource, vs...))
}

// DisconnectSourceNotIn applies the NotIn predicate on the "disconnect_source" field.
func DisconnectSourceNotIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldDisconnectSource, vs...))
}

// DisconnectSourceGT applies the GT predicate on the "disconnect_source" field.
func DisconnectSourceGT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldDisconnectSource, v))
}

// DisconnectSourceGTE applies the GTE predicate on the "disconnect_source" field.
func DisconnectSourceGTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldDisconnectSource, v))
}

// DisconnectSourceLT applies the LT predicate on the "disconnect_source" field.
func DisconnectSourceLT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldDisconnectSource, v))
}

// DisconnectSourceLTE applies the LTE predicate on the "disconnect_source" field.
func DisconnectSourceLTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldDisconnectSource, v))
}

// DisconnectSourceContains applies the Contains predicate on the "disconnect_source" field.
func DisconnectSourceContains(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContains(FieldDisconnectSource, v))
}

// DisconnectSourceHasPrefix applies the HasPrefix predicate on the "disconnect_source" field.
func DisconnectSourceHasPrefix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasPrefix(FieldDisconnectSource, v))
}

// DisconnectSourceHasSuffix applies the HasSuffix predicate on the "disconnect_source" field.
func DisconnectSourceHasSuffix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasSuffix(FieldDisconnectSource, v))
}

// DisconnectSourceEqualFold applies the EqualFold predicate on the "disconnect_source" field.
func DisconnectSourceEqualFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEqualFold(FieldDisconnectSource, v))
}

// DisconnectSourceContainsFold applies the ContainsFold predicate on the "disconnect_source" field.
func DisconnectSourceContainsFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContainsFold(FieldDisconnectSource, v))
}

// UpstreamErrorKindEQ applies the EQ predicate on the "upstream_error_kind" field.
func UpstreamErrorKindEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindNEQ applies the NEQ predicate on the "upstream_error_kind" field.
func UpstreamErrorKindNEQ(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindIn applies the In predicate on the "upstream_error_kind" field.
func UpstreamErrorKindIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldUpstreamErrorKind, vs...))
}

// UpstreamErrorKindNotIn applies the NotIn predicate on the "upstream_error_kind" field.
func UpstreamErrorKindNotIn(vs ...string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldUpstreamErrorKind, vs...))
}

// UpstreamErrorKindGT applies the GT predicate on the "upstream_error_kind" field.
func UpstreamErrorKindGT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindGTE applies the GTE predicate on the "upstream_error_kind" field.
func UpstreamErrorKindGTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindLT applies the LT predicate on the "upstream_error_kind" field.
func UpstreamErrorKindLT(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindLTE applies the LTE predicate on the "upstream_error_kind" field.
func UpstreamErrorKindLTE(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindContains applies the Contains predicate on the "upstream_error_kind" field.
func UpstreamErrorKindContains(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContains(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindHasPrefix applies the HasPrefix predicate on the "upstream_error_kind" field.
func UpstreamErrorKindHasPrefix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasPrefix(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindHasSuffix applies the HasSuffix predicate on the "upstream_error_kind" field.
func UpstreamErrorKindHasSuffix(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldHasSuffix(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindEqualFold applies the EqualFold predicate on the "upstream_error_kind" field.
func UpstreamErrorKindEqualFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEqualFold(FieldUpstreamErrorKind, v))
}

// UpstreamErrorKindContainsFold applies the ContainsFold predicate on the "upstream_error_kind" field.
func UpstreamErrorKindContainsFold(v string) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldContainsFold(FieldUpstreamErrorKind, v))
}

// CollectorVersionEQ applies the EQ predicate on the "collector_version" field.
func CollectorVersionEQ(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldCollectorVersion, v))
}

// CollectorVersionNEQ applies the NEQ predicate on the "collector_version" field.
func CollectorVersionNEQ(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldCollectorVersion, v))
}

// CollectorVersionIn applies the In predicate on the "collector_version" field.
func CollectorVersionIn(vs ...int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldCollectorVersion, vs...))
}

// CollectorVersionNotIn applies the NotIn predicate on the "collector_version" field.
func CollectorVersionNotIn(vs ...int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldCollectorVersion, vs...))
}

// CollectorVersionGT applies the GT predicate on the "collector_version" field.
func CollectorVersionGT(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldCollectorVersion, v))
}

// CollectorVersionGTE applies the GTE predicate on the "collector_version" field.
func CollectorVersionGTE(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldCollectorVersion, v))
}

// CollectorVersionLT applies the LT predicate on the "collector_version" field.
func CollectorVersionLT(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldCollectorVersion, v))
}

// CollectorVersionLTE applies the LTE predicate on the "collector_version" field.
func CollectorVersionLTE(v int16) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldCollectorVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageResponseOutcome) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageResponseOutcome) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageResponseOutcome) predicate.UsageResponseOutcome {
	return predicate.UsageResponseOutcome(sql.NotPredicates(p))
}
