// Code generated by ent, DO NOT EDIT.

package lotteryprizeitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldID, id))
}

// PrizeID applies equality check predicate on the "prize_id" field. It's identical to PrizeIDEQ.
func PrizeID(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldPrizeID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldContent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldStatus, v))
}

// ClaimedBy applies equality check predicate on the "claimed_by" field. It's identical to ClaimedByEQ.
func ClaimedBy(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldClaimedBy, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldClaimedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldCreatedAt, v))
}

// PrizeIDEQ applies the EQ predicate on the "prize_id" field.
func PrizeIDEQ(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldPrizeID, v))
}

// PrizeIDNEQ applies the NEQ predicate on the "prize_id" field.
func PrizeIDNEQ(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldPrizeID, v))
}

// PrizeIDIn applies the In predicate on the "prize_id" field.
func PrizeIDIn(vs ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldPrizeID, vs...))
}

// PrizeIDNotIn applies the NotIn predicate on the "prize_id" field.
func PrizeIDNotIn(vs ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldPrizeID, vs...))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldContainsFold(FieldContent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldContainsFold(FieldStatus, v))
}

// ClaimedByEQ applies the EQ predicate on the "claimed_by" field.
func ClaimedByEQ(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldClaimedBy, v))
}

// ClaimedByNEQ applies the NEQ predicate on the "claimed_by" field.
func ClaimedByNEQ(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldClaimedBy, v))
}

// ClaimedByIn applies the In predicate on the "claimed_by" field.
func ClaimedByIn(vs ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldClaimedBy, vs...))
}

// ClaimedByNotIn applies the NotIn predicate on the "claimed_by" field.
func ClaimedByNotIn(vs ...int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldClaimedBy, vs...))
}

// ClaimedByGT applies the GT predicate on the "claimed_by" field.
func ClaimedByGT(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldClaimedBy, v))
}

// ClaimedByGTE applies the GTE predicate on the "claimed_by" field.
func ClaimedByGTE(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldClaimedBy, v))
}

// ClaimedByLT applies the LT predicate on the "claimed_by" field.
func ClaimedByLT(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldClaimedBy, v))
}

// ClaimedByLTE applies the LTE predicate on the "claimed_by" field.
func ClaimedByLTE(v int64) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldClaimedBy, v))
}

// ClaimedByIsNil applies the IsNil predicate on the "claimed_by" field.
func ClaimedByIsNil() predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIsNull(FieldClaimedBy))
}

// ClaimedByNotNil applies the NotNil predicate on the "claimed_by" field.
func ClaimedByNotNil() predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotNull(FieldClaimedBy))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotNull(FieldClaimedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPrize applies the HasEdge predicate on the "prize" edge.
func HasPrize() predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrizeTable, PrizeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrizeWith applies the HasEdge predicate on the "prize" edge with a given conditions (other predicates).
func HasPrizeWith(preds ...predicate.LotteryPrize) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(func(s *sql.Selector) {
		step := newPrizeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryPrizeItem) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryPrizeItem) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryPrizeItem) predicate.LotteryPrizeItem {
	return predicate.LotteryPrizeItem(sql.NotPredicates(p))
}
