// Code generated by ent, DO NOT EDIT.

package userimage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUserID, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldMode, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldModel, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldPrompt, v))
}

// AspectRatio applies equality check predicate on the "aspect_ratio" field. It's identical to AspectRatioEQ.
func AspectRatio(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldAspectRatio, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldSize, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldImageURL, v))
}

// StorageDriver applies equality check predicate on the "storage_driver" field. It's identical to StorageDriverEQ.
func StorageDriver(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldStorageDriver, v))
}

// StorageObjectKey applies equality check predicate on the "storage_object_key" field. It's identical to StorageObjectKeyEQ.
func StorageObjectKey(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldStorageObjectKey, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldMimeType, v))
}

// Bytes applies equality check predicate on the "bytes" field. It's identical to BytesEQ.
func Bytes(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldBytes, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldCost, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUsageLogID, v))
}

// SourceImageCount applies equality check predicate on the "source_image_count" field. It's identical to SourceImageCountEQ.
func SourceImageCount(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldSourceImageCount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldExpiresAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldUserID, vs...))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldMode, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldModel, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptIsNil applies the IsNil predicate on the "prompt" field.
func PromptIsNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldIsNull(FieldPrompt))
}

// PromptNotNil applies the NotNil predicate on the "prompt" field.
func PromptNotNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldNotNull(FieldPrompt))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldPrompt, v))
}

// AspectRatioEQ applies the EQ predicate on the "aspect_ratio" field.
func AspectRatioEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldAspectRatio, v))
}

// AspectRatioNEQ applies the NEQ predicate on the "aspect_ratio" field.
func AspectRatioNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldAspectRatio, v))
}

// AspectRatioIn applies the In predicate on the "aspect_ratio" field.
func AspectRatioIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldAspectRatio, vs...))
}

// AspectRatioNotIn applies the NotIn predicate on the "aspect_ratio" field.
func AspectRatioNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldAspectRatio, vs...))
}

// AspectRatioGT applies the GT predicate on the "aspect_ratio" field.
func AspectRatioGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldAspectRatio, v))
}

// AspectRatioGTE applies the GTE predicate on the "aspect_ratio" field.
func AspectRatioGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldAspectRatio, v))
}

// AspectRatioLT applies the LT predicate on the "aspect_ratio" field.
func AspectRatioLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldAspectRatio, v))
}

// AspectRatioLTE applies the LTE predicate on the "aspect_ratio" field.
func AspectRatioLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldAspectRatio, v))
}

// AspectRatioContains applies the Contains predicate on the "aspect_ratio" field.
func AspectRatioContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldAspectRatio, v))
}

// AspectRatioHasPrefix applies the HasPrefix predicate on the "aspect_ratio" field.
func AspectRatioHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldAspectRatio, v))
}

// AspectRatioHasSuffix applies the HasSuffix predicate on the "aspect_ratio" field.
func AspectRatioHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldAspectRatio, v))
}

// AspectRatioEqualFold applies the EqualFold predicate on the "aspect_ratio" field.
func AspectRatioEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldAspectRatio, v))
}

// AspectRatioContainsFold applies the ContainsFold predicate on the "aspect_ratio" field.
func AspectRatioContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldAspectRatio, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldSize, v))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldSize, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldImageURL, v))
}

// StorageDriverEQ applies the EQ predicate on the "storage_driver" field.
func StorageDriverEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldStorageDriver, v))
}

// StorageDriverNEQ applies the NEQ predicate on the "storage_driver" field.
func StorageDriverNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldStorageDriver, v))
}

// StorageDriverIn applies the In predicate on the "storage_driver" field.
func StorageDriverIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldStorageDriver, vs...))
}

// StorageDriverNotIn applies the NotIn predicate on the "storage_driver" field.
func StorageDriverNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldStorageDriver, vs...))
}

// StorageDriverGT applies the GT predicate on the "storage_driver" field.
func StorageDriverGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldStorageDriver, v))
}

// StorageDriverGTE applies the GTE predicate on the "storage_driver" field.
func StorageDriverGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldStorageDriver, v))
}

// StorageDriverLT applies the LT predicate on the "storage_driver" field.
func StorageDriverLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldStorageDriver, v))
}

// StorageDriverLTE applies the LTE predicate on the "storage_driver" field.
func StorageDriverLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldStorageDriver, v))
}

// StorageDriverContains applies the Contains predicate on the "storage_driver" field.
func StorageDriverContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldStorageDriver, v))
}

// StorageDriverHasPrefix applies the HasPrefix predicate on the "storage_driver" field.
func StorageDriverHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldStorageDriver, v))
}

// StorageDriverHasSuffix applies the HasSuffix predicate on the "storage_driver" field.
func StorageDriverHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldStorageDriver, v))
}

// StorageDriverEqualFold applies the EqualFold predicate on the "storage_driver" field.
func StorageDriverEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldStorageDriver, v))
}

// StorageDriverContainsFold applies the ContainsFold predicate on the "storage_driver" field.
func StorageDriverContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldStorageDriver, v))
}

// StorageObjectKeyEQ applies the EQ predicate on the "storage_object_key" field.
func StorageObjectKeyEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldStorageObjectKey, v))
}

// StorageObjectKeyNEQ applies the NEQ predicate on the "storage_object_key" field.
func StorageObjectKeyNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldStorageObjectKey, v))
}

// StorageObjectKeyIn applies the In predicate on the "storage_object_key" field.
func StorageObjectKeyIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldStorageObjectKey, vs...))
}

// StorageObjectKeyNotIn applies the NotIn predicate on the "storage_object_key" field.
func StorageObjectKeyNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldStorageObjectKey, vs...))
}

// StorageObjectKeyGT applies the GT predicate on the "storage_object_key" field.
func StorageObjectKeyGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldStorageObjectKey, v))
}

// StorageObjectKeyGTE applies the GTE predicate on the "storage_object_key" field.
func StorageObjectKeyGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldStorageObjectKey, v))
}

// StorageObjectKeyLT applies the LT predicate on the "storage_object_key" field.
func StorageObjectKeyLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldStorageObjectKey, v))
}

// StorageObjectKeyLTE applies the LTE predicate on the "storage_object_key" field.
func StorageObjectKeyLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldStorageObjectKey, v))
}

// StorageObjectKeyContains applies the Contains predicate on the "storage_object_key" field.
func StorageObjectKeyContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldStorageObjectKey, v))
}

// StorageObjectKeyHasPrefix applies the HasPrefix predicate on the "storage_object_key" field.
func StorageObjectKeyHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldStorageObjectKey, v))
}

// StorageObjectKeyHasSuffix applies the HasSuffix predicate on the "storage_object_key" field.
func StorageObjectKeyHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldStorageObjectKey, v))
}

// StorageObjectKeyEqualFold applies the EqualFold predicate on the "storage_object_key" field.
func StorageObjectKeyEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldStorageObjectKey, v))
}

// StorageObjectKeyContainsFold applies the ContainsFold predicate on the "storage_object_key" field.
func StorageObjectKeyContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldStorageObjectKey, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.UserImage {
	return predicate.UserImage(sql.FieldContainsFold(FieldMimeType, v))
}

// BytesEQ applies the EQ predicate on the "bytes" field.
func BytesEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldBytes, v))
}

// BytesNEQ applies the NEQ predicate on the "bytes" field.
func BytesNEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldBytes, v))
}

// BytesIn applies the In predicate on the "bytes" field.
func BytesIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldBytes, vs...))
}

// BytesNotIn applies the NotIn predicate on the "bytes" field.
func BytesNotIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldBytes, vs...))
}

// BytesGT applies the GT predicate on the "bytes" field.
func BytesGT(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldBytes, v))
}

// BytesGTE applies the GTE predicate on the "bytes" field.
func BytesGTE(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldBytes, v))
}

// BytesLT applies the LT predicate on the "bytes" field.
func BytesLT(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldBytes, v))
}

// BytesLTE applies the LTE predicate on the "bytes" field.
func BytesLTE(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldBytes, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldCost, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldNotNull(FieldUsageLogID))
}

// SourceImageCountEQ applies the EQ predicate on the "source_image_count" field.
func SourceImageCountEQ(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldSourceImageCount, v))
}

// SourceImageCountNEQ applies the NEQ predicate on the "source_image_count" field.
func SourceImageCountNEQ(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldSourceImageCount, v))
}

// SourceImageCountIn applies the In predicate on the "source_image_count" field.
func SourceImageCountIn(vs ...int) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldSourceImageCount, vs...))
}

// SourceImageCountNotIn applies the NotIn predicate on the "source_image_count" field.
func SourceImageCountNotIn(vs ...int) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldSourceImageCount, vs...))
}

// SourceImageCountGT applies the GT predicate on the "source_image_count" field.
func SourceImageCountGT(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldSourceImageCount, v))
}

// SourceImageCountGTE applies the GTE predicate on the "source_image_count" field.
func SourceImageCountGTE(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldSourceImageCount, v))
}

// SourceImageCountLT applies the LT predicate on the "source_image_count" field.
func SourceImageCountLT(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldSourceImageCount, v))
}

// SourceImageCountLTE applies the LTE predicate on the "source_image_count" field.
func SourceImageCountLTE(v int) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldSourceImageCount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldNotNull(FieldExpiresAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserImage {
	return predicate.UserImage(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserImage {
	return predicate.UserImage(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserImage {
	return predicate.UserImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserImage {
	return predicate.UserImage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.UserImage {
	return predicate.UserImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.UserImageTask) predicate.UserImage {
	return predicate.UserImage(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserImage) predicate.UserImage {
	return predicate.UserImage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserImage) predicate.UserImage {
	return predicate.UserImage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserImage) predicate.UserImage {
	return predicate.UserImage(sql.NotPredicates(p))
}
